"""
Configuration options for TikZ network visualization.

Port of jar/src/main/java/jline/io/tikz/TikZOptions.java. Fields are plain
attributes (snake_case) and the Java getter/setter spellings are kept, with
setters returning ``self`` so calls chain as in the JAR.
"""


class TikZOptions:
    """Options controlling the TikZ rendering of a Network.

    Attributes:
        node_spacing: vertical spacing between nodes of one layer (cm).
        layer_spacing: horizontal spacing between layers (cm).
        show_routing_prob: show routing probabilities on edges.
        show_server_count: draw the server circle, labelled with the server count.
        show_node_names: label each node with its name.
        show_scheduling: label each queue with its scheduling strategy.
        border_padding: standalone border around the diagram (pt).
        min_prob_to_show: probabilities below this (or above 1 minus it) are hidden.
        hide_auto_generated_nodes: hide auto-generated ``CS_X_to_Y`` ClassSwitch
            nodes and draw the collapsed connections through them.
    """

    _FIELDS = ('node_spacing', 'layer_spacing', 'show_routing_prob', 'show_server_count',
               'show_node_names', 'show_scheduling', 'border_padding', 'min_prob_to_show',
               'hide_auto_generated_nodes')

    def __init__(self, **kwargs):
        self.node_spacing = 3.0
        self.layer_spacing = 4.0
        self.show_routing_prob = True
        self.show_server_count = True
        self.show_node_names = True
        self.show_scheduling = True
        self.border_padding = 10
        self.min_prob_to_show = 0.001
        self.hide_auto_generated_nodes = False
        for key, value in kwargs.items():
            setattr(self, self._canonical(key), value)

    @classmethod
    def _canonical(cls, key):
        """Map a snake_case or camelCase option name to its attribute name."""
        if key in cls._FIELDS:
            return key
        snake = ''.join('_' + c.lower() if c.isupper() else c for c in key)
        if snake in cls._FIELDS:
            return snake
        raise ValueError("Unknown TikZ option '%s'; valid options are %s" % (key, ', '.join(cls._FIELDS)))

    @classmethod
    def from_value(cls, options):
        """Coerce None, a dict of option names, or a TikZOptions into a TikZOptions."""
        if options is None:
            return cls()
        if isinstance(options, TikZOptions):
            return options
        if isinstance(options, dict):
            return cls(**options)
        raise TypeError('TikZ options must be a TikZOptions, a dict or None, not %s' % type(options).__name__)

    def __repr__(self):
        return 'TikZOptions(%s)' % ', '.join('%s=%r' % (f, getattr(self, f)) for f in self._FIELDS)

    # Java-style accessors (setters chain)
    def getNodeSpacing(self):
        return self.node_spacing

    def setNodeSpacing(self, value):
        self.node_spacing = value
        return self

    def getLayerSpacing(self):
        return self.layer_spacing

    def setLayerSpacing(self, value):
        self.layer_spacing = value
        return self

    def isShowRoutingProb(self):
        return self.show_routing_prob

    def setShowRoutingProb(self, value):
        self.show_routing_prob = value
        return self

    def isShowServerCount(self):
        return self.show_server_count

    def setShowServerCount(self, value):
        self.show_server_count = value
        return self

    def isShowNodeNames(self):
        return self.show_node_names

    def setShowNodeNames(self, value):
        self.show_node_names = value
        return self

    def isShowScheduling(self):
        return self.show_scheduling

    def setShowScheduling(self, value):
        self.show_scheduling = value
        return self

    def getBorderPadding(self):
        return self.border_padding

    def setBorderPadding(self, value):
        self.border_padding = value
        return self

    def getMinProbToShow(self):
        return self.min_prob_to_show

    def setMinProbToShow(self, value):
        self.min_prob_to_show = value
        return self

    def isHideAutoGeneratedNodes(self):
        return self.hide_auto_generated_nodes

    def setHideAutoGeneratedNodes(self, value):
        self.hide_auto_generated_nodes = value
        return self
