/*
 * Copyright (c) 2012-2026, QORE Lab, Imperial College London
 * All rights reserved.
 */

package jline.io;

import jline.lang.constant.ActivityPrecedenceType;
import jline.lang.constant.RoutingStrategy;
import jline.lang.constant.SchedStrategy;
import jline.lang.layered.Activity;
import jline.lang.layered.ActivityPrecedence;
import jline.lang.layered.CacheTask;
import jline.lang.layered.Entry;
import jline.lang.layered.Host;
import jline.lang.layered.ItemEntry;
import jline.lang.layered.LayeredNetwork;
import jline.lang.layered.LayeredNetworkElement;
import jline.lang.layered.SetupTask;
import jline.lang.layered.Task;
import jline.lang.processes.Distribution;
import jline.lang.processes.Exp;
import jline.lang.processes.Immediate;
import jline.lang.processes.Replayer;
import jline.lang.processes.Trace;
import jline.util.matrix.Matrix;

import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import static jline.io.CodeGenSupport.cStyleG;
import static jline.io.CodeGenSupport.mstr;
import static jline.io.InputOutput.line_error;
import static jline.io.InputOutput.line_warning;

/**
 * Writes the MATLAB script that rebuilds a {@link LayeredNetwork}, the Java port of MATLAB's {@code LQN2MATLAB}.
 *
 * <p>The script reads the model OBJECTS rather than the struct, and declares the hosts, tasks, entries and
 * activities in model order through the constructors a user would write ({@code Processor}, {@code Task},
 * {@code CacheTask}, {@code SetupTask}, {@code FunctionTask}, {@code Entry}, {@code ItemEntry}, {@code Activity},
 * {@code ActivityPrecedence}), so the regenerated model has the same {@code LayeredNetworkStruct} indexing. Numbers
 * are written at the shortest spelling that reads back bit for bit ({@code %d} for integers, else {@code %.15g} to
 * {@code %.17g}). Blocks: 1 processors, 2 tasks, 3 entries, 4 activities, 5 replies, 6 precedences; no solver lines.
 *
 * <p>Differences forced by the JAR object model: a class or joint dependence handle is a Java lambda and is refused
 * by name; fan-out targets are written in name order (the JAR keeps them in a hash map); entry replies follow
 * activity order; a Coxian is always written in its vector form; and an Immediate think, setup or delay-off time is
 * treated as the constructor default, since the JAR does not distinguish the numeric and object paths there.
 */
public final class LQN2MATLAB {

    private LQN2MATLAB() {
    }

    /** Returns the generated script for a model named after {@code model.getName()}. */
    public static String generate(LayeredNetwork model) {
        return generate(model, model.getName());
    }

    /** Returns the generated script. */
    public static String generate(final LayeredNetwork model, final String modelName) {
        return CodeGenSupport.capture(new CodeGenSupport.Emitter() {
            public void emit(PrintWriter out) {
                LQN2MATLAB.emit(model, modelName, out);
            }
        });
    }

    /** Writes the generated script to a stream (e.g. {@code System.out}), which is flushed but not closed. */
    public static void write(LayeredNetwork model, String modelName, PrintStream out) {
        PrintWriter pw = CodeGenSupport.wrap(out);
        emit(model, modelName, pw);
        pw.flush();
    }

    /** Writes the generated script to a writer, which is flushed but not closed. */
    public static void write(LayeredNetwork model, String modelName, Writer out) {
        PrintWriter pw = CodeGenSupport.wrap(out);
        emit(model, modelName, pw);
        pw.flush();
    }

    /** Writes the generated script to {@code filename}, overwriting it. */
    public static void write(final LayeredNetwork model, final String modelName, String filename) {
        CodeGenSupport.toFile(filename, new CodeGenSupport.Emitter() {
            public void emit(PrintWriter out) {
                LQN2MATLAB.emit(model, modelName, out);
            }
        });
    }

    @SuppressWarnings("deprecation") // FunctionTask is deprecated in the JAR but still a MATLAB constructor
    static void emit(LayeredNetwork model, String modelName, PrintWriter out) {
        List<Host> hosts = ordered(model.getHosts());
        List<Task> tasks = ordered(model.getTasks());
        List<Entry> entries = ordered(model.getEntries());
        List<Activity> acts = ordered(model.getActivities());
        List<String> hostNames = names(hosts);
        List<String> taskNames = names(tasks);
        List<String> entryNames = names(entries);
        List<String> actNames = names(acts);

        out.print("% LayeredNetwork generated by LQN2MATLAB\n");
        out.printf("model = LayeredNetwork(%s);\n", q(modelName));
        out.print("P = {}; T = {}; E = {}; A = {};\n");

        out.print("\n%% Block 1: processors\n");
        for (int p = 0; p < hosts.size(); p++) {
            Host h = hosts.get(p);
            String hv = "P{" + (p + 1) + "}";
            String ctor = h.getClass().getSimpleName();
            if (!ctor.equals("Processor") && !ctor.equals("Host")) {
                ctor = "Processor";
            }
            if (h.getQuantum() != 0.001 || h.getSpeedFactor() != 1) {
                out.printf("%s = %s(model, %s, %s, %s, %s, %s);\n", hv, ctor, q(h.getName()), count(h.getMultiplicity()),
                        schedCode(h.getScheduling()), num(h.getQuantum()), num(h.getSpeedFactor()));
            } else {
                out.printf("%s = %s(model, %s, %s, %s);\n", hv, ctor, q(h.getName()), count(h.getMultiplicity()),
                        schedCode(h.getScheduling()));
            }
            if (h.getReplication() != 1) {
                out.printf("%s.setReplication(%s);\n", hv, count(h.getReplication()));
            }
            emitServerExtras(out, hv, h);
        }

        out.print("\n%% Block 2: tasks\n");
        for (int t = 0; t < tasks.size(); t++) {
            Task tk = tasks.get(t);
            String tv = "T{" + (t + 1) + "}";
            if (tk.getParent() == null) {
                line_error("LQN2MATLAB", "Task " + tk.getName() + " is not placed on a processor.");
            }
            int pidx = hostNames.indexOf(tk.getParent().getName()) + 1;
            if (tk instanceof CacheTask) {
                CacheTask ct = (CacheTask) tk;
                out.printf("%s = CacheTask(model, %s, %s, %s, %s, %s, %s).on(P{%d});\n", tv, q(tk.getName()),
                        count(ct.getItems()), num(ct.getItemLevelCap()), "ReplacementStrategy." + ct.getReplacestrategy().name(),
                        count(tk.getMultiplicity()), schedCode(tk.getScheduling()), pidx);
                if (ct.hasRetrieval()) {
                    out.printf("%s.setRetrieval(true);\n", tv);
                }
            } else if (tk instanceof SetupTask || tk instanceof jline.lang.layered.FunctionTask) {
                out.printf("%s = %s(model, %s, %s, %s).on(P{%d});\n", tv, tk.getClass().getSimpleName(), q(tk.getName()),
                        count(tk.getMultiplicity()), schedCode(tk.getScheduling()), pidx);
            } else {
                if (tk.getClass() != Task.class) {
                    line_warning("LQN2MATLAB", "Task %s is a %s, which LQN2MATLAB declares as a plain Task.",
                            tk.getName(), tk.getClass().getSimpleName());
                }
                out.printf("%s = Task(model, %s, %s, %s).on(P{%d});\n", tv, q(tk.getName()), count(tk.getMultiplicity()),
                        schedCode(tk.getScheduling()), pidx);
            }
            if (!isDefaultTime(tk.getThinkTime())) {
                out.printf("%s.setThinkTime(%s);\n", tv, timeArg(tk.getThinkTime(), tk.getThinkTimeMean()));
            }
            if (!isDefaultTime(tk.getSetupTime())) {
                out.printf("%s.setSetupTime(%s);\n", tv, timeArg(tk.getSetupTime(), tk.getSetupTimeMean()));
            }
            if (!isDefaultTime(tk.getDelayOffTime())) {
                out.printf("%s.setDelayOffTime(%s);\n", tv, timeArg(tk.getDelayOffTime(), tk.getDelayOffTimeMean()));
            }
            if (tk.getReplication() != 1) {
                out.printf("%s.setReplication(%s);\n", tv, count(tk.getReplication()));
            }
            if (tk.getPriority() != 0) {
                out.printf("%s.setPriority(%s);\n", tv, count(tk.getPriority()));
            }
            if (tk.getFanInSource() != null && !tk.getFanInSource().isEmpty()) {
                out.printf("%s.setFanIn(%s, %s);\n", tv, q(tk.getFanInSource()), count(tk.getFanInValue()));
            }
            List<String> fanOut = new ArrayList<String>(tk.getFanOutMap().keySet());
            Collections.sort(fanOut);
            for (String dest : fanOut) {
                out.printf("%s.setFanOut(%s, %s);\n", tv, q(dest), count(tk.getFanOutMap().get(dest)));
            }
            emitServerExtras(out, tv, tk);
        }

        out.print("\n%% Block 3: entries\n");
        for (int e = 0; e < entries.size(); e++) {
            Entry en = entries.get(e);
            String ev = "E{" + (e + 1) + "}";
            if (en.getParent() == null) {
                line_error("LQN2MATLAB", "Entry " + en.getName() + " is not placed on a task.");
            }
            int tidx = taskNames.indexOf(en.getParent().getName()) + 1;
            if (en instanceof ItemEntry) {
                ItemEntry ie = (ItemEntry) en;
                out.printf("%s = ItemEntry(model, %s, %s, %s).on(T{%d});\n", ev, q(en.getName()), count(ie.getCardinality()),
                        dist2code(ie.getPopularity()), tidx);
            } else {
                out.printf("%s = Entry(model, %s).on(T{%d});\n", ev, q(en.getName()), tidx);
            }
            if (en.getType() != null && !en.getType().equals("PH1PH2")) {
                out.printf("%s.setType(%s);\n", ev, q(en.getType()));
            }
            if (en.getArrival() != null) {
                out.printf("%s.setArrival(%s);\n", ev, dist2code(en.getArrival()));
            }
        }
        for (int e = 0; e < entries.size(); e++) {
            Entry en = entries.get(e);
            List<String> dests = values(en.getForwardingDests());
            for (int fw = 0; fw < dests.size(); fw++) {
                out.printf("E{%d}.forward(%s, %s);\n", e + 1, entryRef(dests.get(fw), entryNames), num(en.getForwardingProbs().get(fw)));
            }
        }

        out.print("\n%% Block 4: activities\n");
        for (int a = 0; a < acts.size(); a++) {
            Activity ac = acts.get(a);
            String av = "A{" + (a + 1) + "}";
            if (ac.getParent() == null) {
                line_error("LQN2MATLAB", "Activity " + ac.getName() + " is not placed on a task.");
            }
            int tidx = taskNames.indexOf(ac.getParent().getName()) + 1;
            String bound = "";
            if (ac.getBoundToEntry() != null && !ac.getBoundToEntry().isEmpty()) {
                bound = ".boundTo(" + entryRef(ac.getBoundToEntry(), entryNames) + ")";
            }
            out.printf("%s = Activity(model, %s, %s).on(T{%d})%s;\n", av, q(ac.getName()),
                    timeArg(ac.getHostDemand(), ac.getHostDemandMean()), tidx, bound);
            if (ac.getCallOrder() != null && !ac.getCallOrder().equals("STOCHASTIC")) {
                out.printf("%s.setCallOrder(%s);\n", av, q(ac.getCallOrder()));
            }
            if (!isDefaultTime(ac.getThinkTime())) {
                out.printf("%s.setThinkTime(%s);\n", av, timeArg(ac.getThinkTime(), ac.getThinkTimeMean()));
            }
            if (ac.getPhase() != 1) {
                out.printf("%s.setPhase(%s);\n", av, count(ac.getPhase()));
            }
            List<String> sync = values(ac.getSyncCallDests());
            for (int s = 0; s < sync.size(); s++) {
                out.printf("%s.synchCall(%s, %s);\n", av, entryRef(sync.get(s), entryNames), num(ac.getSyncCallMeans().get(s)));
            }
            // the member calls are declared above, so the grouping is recorded without issuing them again
            for (Activity.CallGroup grp : ac.getSyncCallGroups()) {
                out.printf("%s.recordCallGroup(%s, %s);\n", av, routingCode(grp.strategy), cellstr(grp.dests));
            }
            List<String> async = values(ac.getAsyncCallDests());
            for (int s = 0; s < async.size(); s++) {
                out.printf("%s.asynchCall(%s, %s);\n", av, entryRef(async.get(s), entryNames), num(ac.getAsyncCallMeans().get(s)));
            }
        }

        out.print("\n%% Block 5: replies\n");
        for (int e = 0; e < entries.size(); e++) {
            for (String ractName : values(entries.get(e).getReplyActivity())) {
                int k = actNames.indexOf(ractName);
                boolean isRef = k >= 0 && acts.get(k).getParent() != null
                        && acts.get(k).getParent().getScheduling() == SchedStrategy.REF;
                if (k < 0 || isRef) {
                    // repliesTo refuses a reference-task activity, so the reply is recorded directly
                    out.printf("E{%d}.replyActivity{end+1} = %s;\n", e + 1, q(ractName));
                } else {
                    out.printf("A{%d}.repliesTo(E{%d});\n", k + 1, e + 1);
                }
            }
        }

        out.print("\n%% Block 6: precedences\n");
        for (int t = 0; t < tasks.size(); t++) {
            for (ActivityPrecedence ap : tasks.get(t).getPrecedences()) {
                out.printf("T{%d}.addPrecedence(%s);\n", t + 1, precCode(ap));
            }
        }
    }

    /** Elements of a 0-based index map in index order. */
    private static <T> List<T> ordered(Map<Integer, T> map) {
        List<Integer> keys = new ArrayList<Integer>(map.keySet());
        Collections.sort(keys);
        List<T> list = new ArrayList<T>();
        for (Integer k : keys) {
            list.add(map.get(k));
        }
        return list;
    }

    private static List<String> values(Map<Integer, String> map) {
        return map == null ? new ArrayList<String>() : ordered(map);
    }

    private static List<String> names(List<? extends LayeredNetworkElement> els) {
        List<String> n = new ArrayList<String>();
        for (LayeredNetworkElement el : els) {
            n.add(el.getName());
        }
        return n;
    }

    /** The constructor default: no time, or an Immediate one. */
    private static boolean isDefaultTime(Distribution d) {
        return d == null || d instanceof Immediate;
    }

    /**
     * Argument of a setter that also takes a numeric mean. A numeric argument and a distribution object leave
     * different stored means (Immediate: 1e-8 vs 0; Exp: m vs 1/(1/m)), so the one that reproduces the stored mean is chosen.
     */
    private static String timeArg(Distribution d, double storedMean) {
        if (d instanceof Immediate) {
            return storedMean == 0 ? "Immediate()" : "0";
        }
        if (d instanceof Exp && storedMean != d.getMean() && 1 / storedMean == ((Exp) d).getRate()) {
            return num(storedMean);
        }
        return dist2code(d);
    }

    private static void emitServerExtras(PrintWriter out, String v, LayeredNetworkElement el) {
        if (el.linConA != null && !el.linConA.isEmpty()) {
            out.printf("%s.setConstraint(%s, %s);\n", v, num(el.linConA), num(el.linConB));
        }
        for (LayeredNetworkElement.LinConRow row : el.linConRows) {
            out.printf("%s.addConstraint(%s, %s, %s);\n", v, cellstr(row.names), num(row.coeffs), num(row.cap));
        }
        if (el.lldScaling != null && !el.lldScaling.isEmpty()) {
            out.printf("%s.setLoadDependence(%s);\n", v, num(el.lldScaling));
        }
        if (el.lcdScaling != null || el.ljdScaling != null) {
            line_error("LQN2MATLAB", el.getName() + " declares a class or joint dependence handle, which is a Java function"
                    + " and cannot be written as MATLAB source.");
        }
        for (LayeredNetworkElement.ServerPool pool : el.serverPools) {
            out.printf("%s.addServerType(ServerType(%s, %s, %s, %s));\n", v, q(pool.name), num(pool.count),
                    cellstr(pool.compatible), num(pool.rate));
        }
    }

    /** An ActivityPrecedence, by its named factory when one reproduces it exactly. */
    static String precCode(ActivityPrecedence ap) {
        List<String> pre = ap.getPreActs();
        List<String> post = ap.getPostActs();
        String preT = ap.getPreType();
        String postT = ap.getPostType();
        boolean noPre = isEmpty(ap.getPreParams());
        boolean noPost = isEmpty(ap.getPostParams());
        boolean preSeq = ActivityPrecedenceType.PRE_SEQ.equals(preT);
        if (preSeq && ActivityPrecedenceType.POST_SEQ.equals(postT) && pre.size() == 1 && post.size() == 1 && noPre && noPost) {
            return "ActivityPrecedence.Serial(" + q(pre.get(0)) + ", " + q(post.get(0)) + ")";
        }
        if (ActivityPrecedenceType.PRE_AND.equals(preT) && ActivityPrecedenceType.POST_SEQ.equals(postT) && post.size() == 1 && noPost) {
            if (noPre) {
                return "ActivityPrecedence.AndJoin(" + cellstr(pre) + ", " + q(post.get(0)) + ")";
            }
            return "ActivityPrecedence.AndJoin(" + cellstr(pre) + ", " + q(post.get(0)) + ", " + num(ap.getPreParams()) + ")";
        }
        if (ActivityPrecedenceType.PRE_OR.equals(preT) && ActivityPrecedenceType.POST_SEQ.equals(postT) && post.size() == 1 && noPre && noPost) {
            return "ActivityPrecedence.OrJoin(" + cellstr(pre) + ", " + q(post.get(0)) + ")";
        }
        // the JAR stores an AndFork's post params as all ones (one branch each), which carry no meaning
        if (preSeq && ActivityPrecedenceType.POST_AND.equals(postT) && pre.size() == 1 && noPre && (noPost || allOnes(ap.getPostParams()))) {
            return "ActivityPrecedence.AndFork(" + q(pre.get(0)) + ", " + cellstr(post) + ")";
        }
        if (preSeq && ActivityPrecedenceType.POST_OR.equals(postT) && pre.size() == 1 && noPre) {
            // MATLAB keeps the branch probabilities as a column
            return "ActivityPrecedence.OrFork(" + q(pre.get(0)) + ", " + cellstr(post) + ", " + num(column(ap.getPostParams())) + ")";
        }
        if (preSeq && ActivityPrecedenceType.POST_LOOP.equals(postT) && pre.size() == 1 && noPre) {
            // Loop(pre, {body..., end}, counts): the last post activity is the end activity
            return "ActivityPrecedence.Loop(" + q(pre.get(0)) + ", " + cellstr(post) + ", " + num(ap.getPostParams()) + ")";
        }
        if (preSeq && ActivityPrecedenceType.POST_CACHE.equals(postT) && pre.size() == 1 && noPre && noPost) {
            return "ActivityPrecedence.CacheAccess(" + q(pre.get(0)) + ", " + cellstr(post) + ")";
        }
        return "ActivityPrecedence(" + cellstr(pre) + ", " + cellstr(post) + ", " + precTypeCode(preT) + ", "
                + precTypeCode(postT) + ", " + num(ap.getPreParams()) + ", " + num(ap.getPostParams()) + ")";
    }

    private static boolean allOnes(Matrix m) {
        for (int i = 0; i < m.getNumElements(); i++) {
            if (m.get(i) != 1) {
                return false;
            }
        }
        return true;
    }

    private static Matrix column(Matrix m) {
        if (m == null || m.getNumRows() != 1) {
            return m;
        }
        Matrix c = new Matrix(m.getNumCols(), 1);
        for (int j = 0; j < m.getNumCols(); j++) {
            c.set(j, 0, m.get(0, j));
        }
        return c;
    }

    private static boolean isEmpty(Matrix m) {
        return m == null || m.isEmpty();
    }

    private static String precTypeCode(String type) {
        String[] names = {"PRE_SEQ", "PRE_AND", "PRE_OR", "POST_SEQ", "POST_AND", "POST_OR", "POST_LOOP", "POST_CACHE"};
        String[] texts = {ActivityPrecedenceType.PRE_SEQ, ActivityPrecedenceType.PRE_AND, ActivityPrecedenceType.PRE_OR,
                ActivityPrecedenceType.POST_SEQ, ActivityPrecedenceType.POST_AND, ActivityPrecedenceType.POST_OR,
                ActivityPrecedenceType.POST_LOOP, ActivityPrecedenceType.POST_CACHE};
        for (int k = 0; k < names.length; k++) {
            if (texts[k].equals(type)) {
                return "ActivityPrecedenceType." + names[k];
            }
        }
        line_error("LQN2MATLAB", "Precedence type '" + type + "' has no ActivityPrecedenceType constant.");
        return null;
    }

    private static String schedCode(SchedStrategy s) {
        return "SchedStrategy." + s.name();
    }

    private static String routingCode(RoutingStrategy id) {
        if (id == RoutingStrategy.RROBIN) {
            return "RoutingStrategy.RROBIN";
        }
        if (id == RoutingStrategy.JSQ) {
            return "RoutingStrategy.JSQ";
        }
        line_error("LQN2MATLAB", "Call groups carry RROBIN or JSQ; routing strategy " + id + " cannot be written out.");
        return null;
    }

    /** E{k} for a declared entry, else its name. */
    private static String entryRef(String name, List<String> entryNames) {
        int k = entryNames.indexOf(name);
        return k < 0 ? q(name) : "E{" + (k + 1) + "}";
    }

    /** Constructor call that rebuilds distribution {@code d} with the same parameters. */
    static String dist2code(Distribution d) {
        if (d == null) {
            return "[]";
        }
        String cls = d.getClass().getSimpleName();
        if (d instanceof Trace) {
            return "Trace(" + q(((Trace) d).getFileName()) + ")";
        }
        if (d instanceof Replayer) {
            return "Replayer(" + q(((Replayer) d).getFileName()) + ")";
        }
        switch (cls) {
            case "Immediate":
                return "Immediate()";
            case "Disabled":
                return "Disabled()";
            case "Exp":
            case "Det":
            case "Geometric":
            case "Poisson":
            case "Bernoulli":
                return cls + "(" + par(d, 1) + ")";
            case "Erlang":
            case "Gamma":
            case "Lognormal":
            case "Uniform":
            case "Pareto":
            case "Normal":
            case "Binomial":
            case "DiscreteUniform":
            case "MAP":
            case "ME":
            case "RAP":
            case "Coxian":
            case "DiscreteSampler":
                return cls + "(" + par(d, 1) + ", " + par(d, 2) + ")";
            case "HyperExp":
                if (d.getParam(1).getValue() instanceof Number) {
                    return "HyperExp(" + par(d, 1) + ", " + par(d, 2) + ", " + par(d, 3) + ")";
                }
                return "HyperExp(" + par(d, 1) + ", " + par(d, 2) + ")";
            case "Weibull":
                // params are (scale alpha, shape r), the constructor takes (shape, scale)
                return "Weibull(" + par(d, 2) + ", " + par(d, 1) + ")";
            case "PH":
            case "APH":
                // the JAR stores (n, alpha, T), the MATLAB constructor takes (alpha, T)
                return cls + "(" + par(d, 2) + ", " + par(d, 3) + ")";
            case "MMPP2":
                return "MMPP2(" + par(d, 1) + ", " + par(d, 2) + ", " + par(d, 3) + ", " + par(d, 4) + ")";
            case "Zipf":
                return "Zipf(" + par(d, 3) + ", " + par(d, 4) + ")";
            default:
                line_warning("LQN2MATLAB", "LQN2MATLAB writes the %s distribution as an APH fitted to its mean and SCV.", cls);
                return "APH.fitMeanAndSCV(" + num(d.getMean()) + ", " + num(d.getSCV()) + ")";
        }
    }

    private static String par(Distribution d, int k) {
        return num(d.getParam(k).getValue());
    }

    private static String cellstr(List<String> c) {
        StringBuilder sb = new StringBuilder("{");
        for (int i = 0; i < c.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(q(c.get(i)));
        }
        return sb.append('}').toString();
    }

    /** An int count, with Integer.MAX_VALUE (the JAR's infinity) as Inf. */
    private static String count(int v) {
        return v == Integer.MAX_VALUE ? "Inf" : Integer.toString(v);
    }

    /** A numeric scalar, vector or matrix at the shortest spelling that reads back as the same doubles. */
    static String num(Object v) {
        if (v == null) {
            return "[]";
        }
        if (v instanceof Boolean) {
            return ((Boolean) v) ? "true" : "false";
        }
        if (v instanceof Number) {
            return scalar(((Number) v).doubleValue());
        }
        if (v instanceof Matrix) {
            Matrix m = (Matrix) v;
            if (m.isEmpty()) {
                return "[]";
            }
            if (m.getNumRows() == 1 && m.getNumCols() == 1) {
                return scalar(m.get(0, 0));
            }
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < m.getNumRows(); i++) {
                if (i > 0) {
                    sb.append("; ");
                }
                for (int j = 0; j < m.getNumCols(); j++) {
                    if (j > 0) {
                        sb.append(", ");
                    }
                    sb.append(scalar(m.get(i, j)));
                }
            }
            return sb.append(']').toString();
        }
        List<Double> row = new ArrayList<Double>();
        if (v instanceof double[]) {
            for (double x : (double[]) v) {
                row.add(x);
            }
        } else if (v instanceof int[]) {
            for (int x : (int[]) v) {
                row.add((double) x);
            }
        } else if (v instanceof List) {
            for (Object o : (List<?>) v) {
                if (!(o instanceof Number)) {
                    line_error("LQN2MATLAB", "LQN2MATLAB cannot write a list holding a " + (o == null ? "null" : o.getClass().getSimpleName()) + ".");
                }
                row.add(((Number) o).doubleValue());
            }
        } else if (v instanceof String) {
            return q((String) v);
        } else {
            line_error("LQN2MATLAB", "LQN2MATLAB cannot write a value of type " + v.getClass().getSimpleName() + ".");
        }
        if (row.size() == 1) {
            return scalar(row.get(0));
        }
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < row.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(scalar(row.get(i)));
        }
        return sb.append(']').toString();
    }

    /** One double, round-trip exact: %d for integers below 1e15, else the first of %.15g, %.16g, %.17g that reads back. */
    static String scalar(double v) {
        if (Double.isNaN(v)) {
            return "NaN";
        }
        if (Double.isInfinite(v)) {
            return v > 0 ? "Inf" : "-Inf";
        }
        if (v == Math.rint(v) && Math.abs(v) < 1e15) {
            return Long.toString((long) v);
        }
        String s = null;
        for (int p = 15; p <= 17; p++) {
            s = cStyleG(v, p);
            if (Double.parseDouble(s) == v) {
                return s;
            }
        }
        return s;
    }

    private static String q(String s) {
        return "'" + mstr(s) + "'";
    }
}
