function model = initDefaultCustom(model, nodes)
% This function sets a random initial state for a QN model
% generated by NetworkGenerator. NOTE: This is copied directly from
% LINE's own version, with a slight modification to generate
% only one initial state rather than enumerate all possible states

sn = model.getStruct(false);
R = sn.nclasses;
N = sn.njobs';
if nargin < 2
    nodes = 1:model.getNumberOfNodes;
end
for i=nodes
    if sn.isstation(i)
        n0 = zeros(1,length(N));
        s0 = zeros(1,length(N));
        s = sn.nservers(sn.nodeToStation(i)); % allocate
        for r=find(isfinite(N))' % for all closed classes
            if sn.nodeToStation(i) == sn.refstat(r)
                n0(r) = N(r);
            end
            s0(r) = min(n0(r),s);
            s = s - s0(r);
        end
        state_i = State.fromMarginalAndStarted(sn,i,n0(:)',s0(:)');
        switch sn.nodetype(i)
            case NodeType.Cache
                state_i = [state_i, 1:sn.nvars(i,2*R+1)];
        end
        for r=1:sn.nclasses
            switch sn.routing(i,r)
                case {RoutingStrategy.RROBIN, RoutingStrategy.WRROBIN}
                    % start from first connected queue
                    state_i = [state_i, find(sn.rt(i,:),1)];
            end
        end
        if isempty(state_i)
            error('Default initialization failed on station %d.',i);
        else
            model.nodes{i}.setState(state_i);
            prior_state_i = zeros(1,size(state_i,1)); prior_state_i(1) = 1;
            model.nodes{i}.setStatePrior(prior_state_i);
        end
    elseif sn.isstateful(i) % not a station
        switch class(model.nodes{i})
            case 'Cache'
                state_i = zeros(1,model.getNumberOfClasses);
                state_i = [state_i, 1:sum(model.nodes{i}.itemLevelCap)];
                model.nodes{i}.setState(state_i);
            case 'Router'
                model.nodes{i}.setState([1]);
            otherwise
                model.nodes{i}.setState([]);
        end
        %error('Default initialization not available on stateful node %d.',i);
    end
end
end

