%% BASIC
%% cache_replc_rr
clearvars; test_cache_replc_rr;
%% cache_replc_fifo
clearvars; test_cache_replc_fifo;
%% cache_replc_routing
clearvars; test_cache_replc_routing;
% cache_replc_lru
%clearvars; test_cache_replc_lru;
%% cache_compare_replc
clearvars; test_cache_compare_replc;
%% cs_implicit
clearvars; test_cs_implicit;
%% cqn_repairmen
clearvars; test_cqn_repairmen;
%% cqn_twoclass_hyperl
clearvars; test_cqn_twoclass_hyperl;
%% cqn_threeclass_hyperl
clearvars; test_cqn_threeclass_hyperl;
%% cqn_multiserver
clearvars; test_cqn_multiserver;
%% cqn_oneline
clearvars; test_cqn_oneline;
%% cqn_twoclass_erl
clearvars; test_cqn_twoclass_erl;
%% cqn_bcmp_theorem
clearvars; test_cqn_bcmp_theorem;
%% cqn_repairmen_multi
clearvars; test_cqn_repairmen_multi;
%% cqn_twoqueues_multi
clearvars; test_cqn_twoqueues_multi;
%% fj_basic_open
clearvars; test_fj_basic_open;
%% fj_twoclasses_forked
clearvars; test_fj_twoclasses_forked;
%% fj_basic_nesting
clearvars; test_fj_basic_nesting;
%% fj_nojoin
clearvars; test_fj_nojoin;
%% fj_basic_closed
clearvars; test_fj_basic_closed;
%% fj_serialfjs_open
clearvars; test_fj_serialfjs_open;
%% fj_cs_postfork
clearvars; test_fj_cs_postfork;
%% fj_cs_multi_visits
clearvars; test_fj_cs_multi_visits;
%% lqn_serial
clearvars; test_lqn_serial;
%% lqn_multi_solvers
clearvars; test_lqn_multi_solvers;
%% lqn_twotasks
clearvars; test_lqn_twotasks;
%% lqn_bpmn
%clearvars; test_lqn_bpmn;
%% mqn_basic
clearvars; test_mqn_basic;
%% mqn_multiserver_ps
clearvars; test_mqn_multiserver_ps;
%% mqn_multiserver_fcfs
clearvars; test_mqn_multiserver_fcfs;
%% mqn_singleserver_fcfs
clearvars; test_mqn_singleserver_fcfs;
%% mqn_singleserver_ps
clearvars; test_mqn_singleserver_ps;
%% oqn_basic
clearvars; test_oqn_basic;
%% oqn_oneline
clearvars; test_oqn_oneline;
%% oqn_cs_routing
clearvars; test_oqn_cs_routing;
%% oqn_trace_driven
clearvars; test_oqn_trace_driven;
%% oqn_vsinks
clearvars; test_oqn_vsinks;
%% oqn_fourqueues
clearvars; test_oqn_fourqueues;
%% prio_hol_open
clearvars; test_prio_hol_open;
%% prio_hol_closed
clearvars; test_prio_hol_closed;
%% prio_psprio
clearvars; test_prio_psprio;
%% prio_identical
clearvars; test_prio_identical;
%% spn_basic_open
clearvars; test_spn_basic_open;
%% spn_open_sevenplaces
clearvars; test_spn_open_sevenplaces;

%% ADVANCED
%% cdf_respt_closed
clearvars; test_cdf_respt_closed;
%% cdf_respt_closed_threeclasses
clearvars; test_cdf_respt_closed_threeclasses;
%% cdf_respt_open_twoclasses
%clearvars; test_cdf_respt_open_twoclasses;
%% cdf_respt_distrib
clearvars; test_cdf_respt_distrib;
% cdf_respt_other
%clearvars; test_cdf_respt_other;
%% init_state_fcfs_exp
clearvars; test_init_state_fcfs_exp;
%% init_state_fcfs_nonexp
clearvars; test_init_state_fcfs_nonexp;
%% init_state_ps
clearvars; test_init_state_ps;
%% lcq_singlehost
clearvars; test_lcq_singlehost;
%% lcq_threehosts
clearvars; test_lcq_threehosts;
%% ld_multiserver_fcfs
clearvars; test_ld_multiserver_fcfs;
%% ld_multiserver_ps_twoclasses
clearvars; test_ld_multiserver_ps_twoclasses;
%% ld_multiserver_ps
clearvars; test_ld_multiserver_ps;
% ld_heterogeneous_fcfs
%clearvars; test_ld_heterogeneous_fcfs;
%% ld_class_dependence
clearvars; test_ld_class_dependence;
%% ld_joint_dependence
clearvars; test_ld_joint_dependence;
% misc_trace_analysis
%clearvars; test_misc_trace_analysis;
% misc_rare_events
%clearvars; test_misc_rare_events;
%% cqn_scheduling_dps
clearvars; test_cqn_scheduling_dps;
%% cqn_mmpp2_service
clearvars; test_cqn_mmpp2_service;
%% renv_twostages_repairmen
clearvars; test_renv_twostages_repairmen;
%% renv_fourstages_repairmen
clearvars; test_renv_fourstages_repairmen;
% renv_fourstages_repairmen_2
%clearvars; test_renv_fourstages_repairmen_2;
%% sdroute_closed
clearvars; test_sdroute_closed;
%% sdroute_twoclasses_closed
clearvars; test_sdroute_twoclasses_closed;
%% sdroute_open
clearvars; test_sdroute_open;
%% statepr_aggr
clearvars; test_statepr_aggr;
%% statepr_aggr_large
clearvars; test_statepr_aggr_large;
%% statepr_sys_aggr
clearvars; test_statepr_sys_aggr;
%% statepr_sys_aggr_large
clearvars; test_statepr_sys_aggr_large;
%% statepr_allprobs_ps
clearvars; test_statepr_allprobs_ps;
%% statepr_allprobs_fcfs
clearvars; test_statepr_allprobs_fcfs;
%% svcestimation_1
%clearvars; test_svcestimation_1;
%% svcestimation_2
%clearvars; test_svcestimation_2;
%% svcestimation_3
%clearvars; test_svcestimation_3;
%% svcestimation_4
%clearvars; test_svcestimation_4;
%% bolch_sum_ch10_12
clearvars; test_bolch_sum_ch10_12;
%% bolch_sum_ch10_13
clearvars; test_bolch_sum_ch10_13;
