classdef SolverFeatureSet < handle
    % An auxiliary class to specify the features supported by a solver.
    %
    % Copyright (c) 2012-2026, Imperial College London
    % All rights reserved.
    
    properties
        list; % list of features
    end
    
    properties (Constant)
        % Canonical feature-name registry; must stay identical to
        % jar FeatureSet.java and python base.py SolverFeatureSet.FIELDS.
        % It also lists the distributions that no solver supports as a service
        % or arrival process (DiscreteSampler, DiscreteUniform, Empirical, GMM,
        % MMDP, MMDP2, MMPP, MultivariateNormal, NegBinomial, Prior, Zipf):
        % their names can still be emitted by getUsedLangFeatures, and an
        % unregistered name is invisible to SUPPORTS, which iterates this list,
        % so the model would pass the support gate as if the distribution were
        % absent. No solver declares them, hence a clean rejection instead.
        fields = {'ClassSwitch',...
            'Cache', ...
            'Delay', ...
            'DelayStation',...
            'Fork',...
            'Join',...
            'Logger',...
            'Place', ...
            'QueueingPlace', ...
            'Queue', ...
            'JobSink',...
            'Sink',...
            'Source',...
            'Router',...
            'Transition', ...
            'Coxian',...
            'Cox2',...
            'APH',...
            'Det', ...
            'Disabled',...
            'Erlang',...
            'Exp',...
            'Gamma',...
            'HyperExp', ...
            'Immediate',...
            'Lognormal',...
            'MAP',...
            'DMAP',...
            'MMAP',...
            'BMAP',...
            'MMPP2',...
            'NHPP',...
            'EmpiricalCdf',... % name declared by EmpiricalCDF.m, not the JSON wire type
            'Expolynomial',...
            'Normal',...
            'Pareto',...
            'PH',...
            'ME',...
            'RAP',...
            'Replayer',...
            'Trace',...
            'Uniform', ...
            'Weibull',...
            'Bernoulli',...
            'Binomial',...
            'Geometric',...
            'Poisson',...
            'DiscreteSampler',...
            'DiscreteUniform',...
            'Empirical',...
            'GMM',...
            'MMDP',...
            'MMDP2',...
            'MMPP',...
            'MultivariateNormal',...
            'NegBinomial',...
            'Prior',...
            'Zipf',...
            'StatelessClassSwitcher',...
            'CacheClassSwitcher',...
            'CacheRetrieval',...
            'InfiniteServer',...
            'Forker',...
            'Joiner',...
            'LogTunnel', ...
            'SharedServer', ...
            'Buffer', ...
            'Region', ...
            'Linkage',...
            'Enabling', ...
            'Inhibiting', ...
            'Timing', ...
            'Firing', ...
            'Storage', ...
            'RandomSource', ...
            'Dispatcher', ...
            'Server', ...
            'ServiceTunnel', ...
            'RoutingStrategy_PROB', ...
            'RoutingStrategy_RAND', ...
            'RoutingStrategy_RROBIN', ...
            'RoutingStrategy_WRROBIN', ...
            'RoutingStrategy_JSQ', ...
            'RoutingStrategy_SQ', ...
            'RoutingStrategy_RL', ...
            'SchedStrategy_INF', ...
            'SchedStrategy_FCFS', ...
            'SchedStrategy_FCFSPR', ...
            'SchedStrategy_FCFSPI', ...
            'SchedStrategy_FCFSPRIO', ...
            'SchedStrategy_FCFSPRPRIO', ...
            'SchedStrategy_FCFSPIPRIO', ...
            'SchedStrategy_LCFS', ...
            'SchedStrategy_LCFSPR', ...
            'SchedStrategy_LCFSPI', ...
            'SchedStrategy_LCFSPRIO', ...
            'SchedStrategy_LCFSPRPRIO', ...
            'SchedStrategy_LCFSPIPRIO', ...
            'SchedStrategy_SEPT', ...
            'SchedStrategy_LEPT', ...
            'SchedStrategy_SJF', ...
            'SchedStrategy_LJF', ...
            'SchedStrategy_SRPT', ...
            'SchedStrategy_SRPTPRIO', ...
            'SchedStrategy_PSJF', ...
            'SchedStrategy_FB', ...
            'SchedStrategy_LRPT', ...
            'SchedStrategy_SETF', ...
            'SchedStrategy_FSP', ...
            'SchedStrategy_PAS', ...
            'SchedStrategy_OI', ...
            'SchedStrategy_PS', ...
            'SchedStrategy_DPS', ...
            'SchedStrategy_GPS', ...
            'SchedStrategy_PSPRIO', ...
            'SchedStrategy_DPSPRIO', ...
            'SchedStrategy_GPSPRIO', ...
            'SchedStrategy_SIRO', ...
            'SchedStrategy_HOL', ...
            'SchedStrategy_EXT', ...
            'SchedStrategy_POLLING', ...
            'SchedStrategy_EDD', ...
            'SchedStrategy_EDF', ...
            'SchedStrategy_LPS', ...
            'ReplacementStrategy_RR', ...
            'ReplacementStrategy_FIFO', ...
            'ReplacementStrategy_SFIFO', ...
            'ReplacementStrategy_LRU', ...
            'ReplacementStrategy_HLRU', ...
            'ReplacementStrategy_CLIMB', ...
            'ReplacementStrategy_QLRU', ...
            'ClosedClass', ...
            'OpenClass', ...
            'SelfLoopingClass', ...
            'OpenSignal', ...
            'ClosedSignal', ...
            'SignalType_NEGATIVE', ...
            'SignalType_REPLY', ...
            'SignalType_CATASTROPHE', ...
            'SignalBatchRemoval', ...
            'SignalRemovalPolicy', ...
            'BatchArrival', ...
            'LoadDependence', ...
            'ClassDependence', ...
            'JointDependence', ...
            'SetupDelayOff', ...
            'Retrial', ...
            'Balking', ...
            'Reneging', ...
            'Breakdown', ...
            'Host', ...
            'Processor', ...
            'Task', ...
            'Entry', ...
            'Activity', ...
            'SyncCall', ...
            'AsyncCall', ...
            'ActivityPrecedence_PRE_SEQ', ...
            'ActivityPrecedence_POST_SEQ', ...
            'ActivityPrecedence_PRE_AND', ...
            'ActivityPrecedence_POST_AND', ...
            'ActivityPrecedence_PRE_OR', ...
            'ActivityPrecedence_POST_OR', ...
            'SchedStrategy_REF'};
    end
    
    methods
        function self = SolverFeatureSet()
            % SELF = SOLVERFEATURESET()
            
            % Nodes and Stations
            fields = SolverFeatureSet.fields;
            for f=1:length(fields)
                self.list.(fields{f})=false;
            end
        end
        
        function self = setTrue(self, feature)
            % SELF = SETTRUE(FEATURE)
            
            if iscell(feature)
                for c=1:length(feature)
                    self.setTrue(feature{c});
                end
            else
                if ~strcmpi(feature,'char') && isfield(self.list, feature)
                    % Unregistered names are ignored on purpose: unlike the jar,
                    % which curates every name it records, MNetwork.addNode
                    % feeds raw node and section class names (Section,
                    % InputSection, ServiceSection, ClassSwitcher, ...) that
                    % denote no capability and that no solver declares, so
                    % registering them would reject every model. The corollary
                    % is that a genuine capability name missing from FIELDS is
                    % silently unenforced: keep FIELDS identical to jar
                    % FeatureSet.java and python SolverFeatureSet.FIELDS.
                    self.list.(feature) = true;
                end
            end
        end
        
        function self = setFalse(self, feature)
            % SELF = SETFALSE(FEATURE)
            
            if iscell(feature)
                for c=1:length(feature)
                    self.setFalse(feature{c});
                end
            else
                if isfield(self.list, feature) % see SETTRUE
                    self.list.(feature) = false;
                end
            end
        end
        
    end
    
    methods(Static)
        function [bool, reason] = supports(featSupportedList, featUsedList)
            % [BOOL, REASON] = SUPPORTS(FEATSUPPORTEDLIST, FEATUSEDLIST)
            %
            % BOOL is true when every feature used by the model is supported.
            % REASON is a human-readable list of the offending feature names
            % (empty when BOOL is true), for use in method-aware error messages.

            bool = true;
            unsupported = {};

            % Nodes and Stations
            fields = SolverFeatureSet.fields;
            for f=1:length(fields)
                if featUsedList.list.(fields{f}) > featSupportedList.list.(fields{f})
                    bool = false;
                    unsupported{end+1} = fields{f}; %#ok<AGROW>
                end
            end

            reason = '';
            if ~isempty(unsupported)
                str='Some features are not supported by the chosen solver (feature: ';
                for u=1:length(unsupported)
                    if u==1
                        str = sprintf('%s%s',str,unsupported{u});
                    else
                        str = sprintf('%s, %s',str,unsupported{u});
                    end
                end
                str = sprintf('%s).\n',str);
                reason = str;
                % Preserve the historical side-effect warning for the coarse
                % (solver-level) callers that do not consume REASON.
                if nargout < 2
                    line_warning(mfilename,str);
                end
            end
        end
    end
end
