classdef SolverFeatureSet < handle
    % An auxiliary class to specify the features supported by a solver.
    %
    % Copyright (c) 2012-2026, Imperial College London
    % All rights reserved.
    
    properties
        list; % list of features
    end
    
    properties (Constant)
        % Canonical feature-name registry; must stay identical to
        % jar FeatureSet.java and python base.py SolverFeatureSet.FIELDS.
        % It also lists the distributions that no solver supports as a service
        % or arrival process (DiscreteSampler, DiscreteUniform, Empirical, GMM,
        % MMDP, MMDP2, MMPP, MultivariateNormal, NegBinomial, Prior, Zipf):
        % their names can still be emitted by getUsedLangFeatures, and an
        % unregistered name is invisible to SUPPORTS, which iterates this list,
        % so the model would pass the support gate as if the distribution were
        % absent. No solver declares them, hence a clean rejection instead.
        fields = {'ClassSwitch',...
            'Cache', ...
            'Delay', ...
            'DelayStation',...
            'Fork',...
            'Join',...
            'Logger',...
            'Place', ...
            'QueueingPlace', ...
            'Queue', ...
            'JobSink',...
            'Sink',...
            'Source',...
            'Router',...
            'Transition', ...
            'Coxian',...
            'Cox2',...
            'APH',...
            'Det', ...
            'Disabled',...
            'Erlang',...
            'Exp',...
            'Gamma',...
            'HyperExp', ...
            'Immediate',...
            'Lognormal',...
            'MAP',...
            'DMAP',...
            'MMAP',...
            'BMAP',...
            'MMPP2',...
            'NHPP','MAPt','PHt',...
            'EmpiricalCdf',... % name declared by EmpiricalCDF.m, not the JSON wire type
            'Expolynomial',...
            'Normal',...
            'Pareto',...
            'PH',...
            'ME',...
            'RAP',...
            'Replayer',...
            'Trace',...
            'Uniform', ...
            'Weibull',...
            'Bernoulli',...
            'Binomial',...
            'Geometric',...
            'Poisson',...
            'DiscreteSampler',...
            'DiscreteUniform',...
            'Empirical',...
            'GMM',...
            'MMDP',...
            'MMDP2',...
            'MMPP',...
            'MultivariateNormal',...
            'NegBinomial',...
            'Prior',...
            'Zipf',...
            'StatelessClassSwitcher',...
            'CacheClassSwitcher',...
            'CacheRetrieval',...
            'InfiniteServer',...
            'Forker',...
            'Joiner',...
            'JoinPartial',... % quorum join: k of n siblings, k < n
            'LogTunnel', ...
            'SharedServer', ...
            'Buffer', ...
            'Region', ...
            'Linkage',...
            'Enabling', ...
            'Inhibiting', ...
            'Timing', ...
            'Firing', ...
            'Storage', ...
            'RandomSource', ...
            'Dispatcher', ...
            'Server', ...
            'ServiceTunnel', ...
            'RoutingStrategy_PROB', ...
            'RoutingStrategy_RAND', ...
            'RoutingStrategy_RROBIN', ...
            'RoutingStrategy_WRROBIN', ...
            'RoutingStrategy_JSQ', ...
            'RoutingStrategy_SQ', ...
            'RoutingStrategy_SDR', ...
            'SchedStrategy_INF', ...
            'SchedStrategy_FCFS', ...
            'SchedStrategy_FCFSPR', ...
            'SchedStrategy_FCFSPI', ...
            'SchedStrategy_FCFSPRIO', ...
            'SchedStrategy_FCFSPRPRIO', ...
            'SchedStrategy_FCFSPIPRIO', ...
            'SchedStrategy_LCFS', ...
            'SchedStrategy_LCFSPR', ...
            'SchedStrategy_LCFSPI', ...
            'SchedStrategy_LCFSPRIO', ...
            'SchedStrategy_LCFSPRPRIO', ...
            'SchedStrategy_LCFSPIPRIO', ...
            'SchedStrategy_SEPT', ...
            'SchedStrategy_LEPT', ...
            'SchedStrategy_SJF', ...
            'SchedStrategy_LJF', ...
            'SchedStrategy_SRPT', ...
            'SchedStrategy_SRPTPRIO', ...
            'SchedStrategy_PSJF', ...
            'SchedStrategy_FB', ...
            'SchedStrategy_LRPT', ...
            'SchedStrategy_SETF', ...
            'SchedStrategy_FSP', ...
            'SchedStrategy_PAS', ...
            'SchedStrategy_OI', ...
            'SchedStrategy_PS', ...
            'SchedStrategy_DPS', ...
            'SchedStrategy_GPS', ...
            'SchedStrategy_PSPRIO', ...
            'SchedStrategy_DPSPRIO', ...
            'SchedStrategy_GPSPRIO', ...
            'SchedStrategy_SIRO', ...
            'SchedStrategy_HOL', ...
            'SchedStrategy_EXT', ...
            'SchedStrategy_POLLING', ...
            'SchedStrategy_EDD', ...
            'SchedStrategy_EDF', ...
            'SchedStrategy_LPS', ...
            'ReplacementStrategy_RR', ...
            'ReplacementStrategy_FIFO', ...
            'ReplacementStrategy_SFIFO', ...
            'ReplacementStrategy_LRU', ...
            'ReplacementStrategy_HLRU', ...
            'ReplacementStrategy_CLIMB', ...
            'ReplacementStrategy_QLRU', ...
            'ClosedClass', ...
            'OpenClass', ...
            'SelfLoopingClass', ...
            'OpenSignal', ...
            'ClosedSignal', ...
            'SignalType_NEGATIVE', ...
            'SignalType_REPLY', ...
            'SignalType_CATASTROPHE', ...
            'SignalBatchRemoval', ...
            'SignalRemovalPolicy', ...
            'BatchArrival', ...
            'CacheItemSize', ...
            'LoadDependence', ...
            'ClassDependence', ...
            'JointDependence', ...
            'GlobalDependence', ...
            'SetupDelayOff', ...
            'ServerParallelism', ...
            'Retrial', ...
            'Balking', ...
            'Reneging', ...
            'Breakdown', ...
            'Host', ...
            'Processor', ...
            'Task', ...
            'Entry', ...
            'Activity', ...
            'SyncCall', ...
            'AsyncCall', ...
            'ActivityPrecedence_PRE_SEQ', ...
            'ActivityPrecedence_POST_SEQ', ...
            'ActivityPrecedence_PRE_AND', ...
            'ActivityPrecedence_POST_AND', ...
            'ActivityPrecedence_PRE_OR', ...
            'ActivityPrecedence_POST_OR', ...
            'SchedStrategy_REF', ...
            ... Layered cache-queueing models: a CacheTask holds a segmented
            ... cache whose items are ItemEntry entries, and a read is a call to
            ... one of them whose bound activity branches on a POST_CACHE
            ... precedence into hit and miss. Registered in all four codebases
            ... because the jar SolverLDES.getLNFeatureSet DECLARES all three,
            ... and there an unregistered name is a hard error, so that whole
            ... feature set threw before it could compare anything.
            'CacheTask', ...
            'ItemEntry', ...
            'ActivityPrecedence_POST_CACHE', ...
            ... Variable forking levels. A Fork emits tasksPerLink jobs on every
            ... outgoing link; these three name the ways that degree stops being
            ... one number. ForkFanoutVector: the count differs by destination
            ... or by class (sn.nodeparam{f}.fanOutLink). ForkFanoutRandom: the
            ... count is a draw from a DiscreteSampler, redrawn per link and per
            ... forked job (sn.nodeparam{f}.fanOutDist). ForkBranchProbability:
            ... a branch fires only with probability p, so the SIBLING COUNT is
            ... random even when each link carries a fixed number
            ... (sn.nodeparam{f}.fanOutProb). Appended at the tail so every
            ... earlier index is unchanged.
            'ForkFanoutVector', ...
            'ForkFanoutRandom', ...
            'ForkBranchProbability', ...
            ... Two names the C++ port carried alone until 2026-08-22, for
            ... capabilities this codebase can express but no gate could see.
            ... HeteroServers: Queue.addServerType gives a station several
            ... server POOLS with their own counts, class compatibilities and
            ... per-(type,class) rates (sn.nodeparam{i}.nservertypes and the
            ... servertypenames/serverspertype/servercompat/heterorates block).
            ... Only SolverJMT and the LDES engine honour them; every other
            ... solver reads sn.nservers and answers for a homogeneous station,
            ... which is a different system. DepartureDiscipline:
            ... Place.setDepartureDiscipline(class, FIFO) makes the depository
            ... release a served token only after the earlier ones, which
            ... changes which transitions are enabled. NO solver implements it
            ... in any codebase, so declaring it nowhere is the point -- the
            ... model is refused instead of being solved as if NORMAL.
            'HeteroServers', ...
            'DepartureDiscipline', ...
            ... MATLAB-FIRST (2026-09-05): these two are registered HERE ONLY
            ... for now, so the identity rule at the top of this list is broken
            ... on purpose until the jar FeatureSet.java and the python
            ... base.py FIELDS append the same two names, in this order, in the
            ... follow-up port. Both are "having something" properties that the
            ... registry could not name, so every rule about them lived only
            ... in structural predicates and was invisible to model.help.
            ... MultiServer: a finite-server station serving more than one job
            ... at once, i.e. a Queue whose numberOfServers is finite and > 1
            ... (a Delay / INF station is not one). FiniteCapacity: a station
            ... or per-class buffer that can BIND, exactly the condition
            ... MNetwork.findBindingCapacity tests (node-level cap / classCap
            ... below the population that can reach it; an open class always
            ... binds; a Cache model is exempt), which is also what
            ... NetworkSolver.checkBindingCapacity refuses on.
            'MultiServer', ...
            'FiniteCapacity'};
    end
    
    methods
        function self = SolverFeatureSet()
            % SELF = SOLVERFEATURESET()
            
            % Nodes and Stations
            fields = SolverFeatureSet.fields;
            for f=1:length(fields)
                self.list.(fields{f})=false;
            end
        end
        
        function self = setTrue(self, feature)
            % SELF = SETTRUE(FEATURE)
            
            if iscell(feature)
                for c=1:length(feature)
                    self.setTrue(feature{c});
                end
            else
                if ~strcmpi(feature,'char') && isfield(self.list, feature)
                    % Unregistered names are ignored on purpose: unlike the jar,
                    % which curates every name it records, MNetwork.addNode
                    % feeds raw node and section class names (Section,
                    % InputSection, ServiceSection, ClassSwitcher, ...) that
                    % denote no capability and that no solver declares, so
                    % registering them would reject every model. The corollary
                    % is that a genuine capability name missing from FIELDS is
                    % silently unenforced: keep FIELDS identical to jar
                    % FeatureSet.java and python SolverFeatureSet.FIELDS.
                    self.list.(feature) = true;
                end
            end
        end
        
        function self = setFalse(self, feature)
            % SELF = SETFALSE(FEATURE)
            
            if iscell(feature)
                for c=1:length(feature)
                    self.setFalse(feature{c});
                end
            else
                if isfield(self.list, feature) % see SETTRUE
                    self.list.(feature) = false;
                end
            end
        end
        
    end
    
    methods(Static)
        function general = generalizationOf(feature)
            % GENERAL = GENERALIZATIONOF(FEATURE)
            %
            % The registry name a specialization falls back to when it is not
            % declared, or '' when the feature stands on its own.
            %
            % A few entries name a SPECIAL CASE of another entry rather than a
            % capability of their own: 'Cox2' is a Coxian restricted to two
            % phases and 'Trace' is a Replayer under another class name. Marking
            % a model with only the general name left the specific entry
            % unreachable, which is dead registry surface; marking it with the
            % specific name alone would instead REJECT the model at every solver
            % declaring only the general one, i.e. at every solver that accepts
            % it today. So getUsedLangFeatures marks the most specific name and
            % SUPPORTS falls back here. The fallback runs one way only: a solver
            % supporting just the special case declares 'Cox2' alone and keeps
            % refusing a five-phase Coxian.
            switch feature
                case 'Cox2'
                    general = 'Coxian';
                case 'Trace'
                    general = 'Replayer';
                otherwise
                    general = '';
            end
        end

        function [bool, reason, unsupported] = supports(featSupportedList, featUsedList)
            % [BOOL, REASON, UNSUPPORTED] = SUPPORTS(FEATSUPPORTEDLIST, FEATUSEDLIST)
            %
            % BOOL is true when every feature used by the model is supported.
            % REASON is a human-readable list of the offending feature names
            % (empty when BOOL is true), for use in method-aware error messages.
            % UNSUPPORTED is the same list as a cell array of feature names, for
            % dispatch decisions that depend on which features are missing.

            bool = true;
            unsupported = {};

            % Nodes and Stations
            fields = SolverFeatureSet.fields;
            for f=1:length(fields)
                if featUsedList.list.(fields{f}) > featSupportedList.list.(fields{f})
                    % A specialization the solver did not name is covered by the
                    % general capability when that one IS declared.
                    general = SolverFeatureSet.generalizationOf(fields{f});
                    if ~isempty(general) && featSupportedList.list.(general)
                        continue
                    end
                    bool = false;
                    unsupported{end+1} = fields{f}; %#ok<AGROW>
                end
            end

            reason = '';
            if ~isempty(unsupported)
                str='Some features are not supported by the chosen solver (feature: ';
                for u=1:length(unsupported)
                    if u==1
                        str = sprintf('%s%s',str,unsupported{u});
                    else
                        str = sprintf('%s, %s',str,unsupported{u});
                    end
                end
                str = sprintf('%s).\n',str);
                reason = str;
                % Preserve the historical side-effect warning for the coarse
                % (solver-level) callers that do not consume REASON.
                if nargout < 2
                    line_warning(mfilename,str);
                end
            end
        end
    end
end
