/*
 * Copyright (c) 2012-2026, QORE Lab, Imperial College London
 * All rights reserved.
 *
 * Self-contained LQN/queueing parameter estimators. Oracles:
 *   1. Conservation of the event replay: the queue length reconstructed at
 *      each arrival is integer-valued, non-negative, and returns to zero once
 *      every job has departed. Asserted EXACTLY, in rationals.
 *   2. infer_qmle inverted: feeding it queue lengths generated by the same
 *      arrival-theorem relation returns the demands it was built from, as an
 *      identity between rationals.
 *   3. infer_rps against the closed form of the single-column non-negative
 *      least squares problem, computed by hand.
 *   4. infer_lqn_jacobian against the exact Jacobian of an affine map, for
 *      which the forward difference has no truncation error at all.
 *   5. MATLAB reference values from matlab/src/api/infer/*.m.
 */
#include <cmath>
#include <functional>
#include <string>
#include <vector>

#include "doctest.h"
#include "line/api/infer/infer_compute_ql_at_arrival.h"
#include "line/api/infer/infer_get_qlen_arrival.h"
#include "line/api/infer/infer_lqn_ekf.h"
#include "line/api/infer/infer_lqn_findbyname.h"
#include "line/api/infer/infer_lqn_getobs.h"
#include "line/api/infer/infer_lqn_jacobian.h"
#include "line/api/infer/infer_qmle.h"
#include "line/api/infer/infer_rps.h"

using line::Matrix;
using line::Rational;
using line::Real50;
using line::infer::infer_compute_ql_at_arrival;
using line::infer::infer_get_qlen_arrival;
using line::infer::infer_lqn_jacobian;
using line::infer::infer_qmle;
using line::infer::infer_rps;

namespace {

double rel(double got, double want) {
    const double d = std::fabs(got - want);
    return std::fabs(want) > 1e-30 ? d / std::fabs(want) : d;
}

}  // namespace

TEST_CASE("infer_qmle hand values, exactly") {
    // Q = [1 2; 1/2 1], N = [4 5], Z = [1 2]. Each entry is
    // Q(i,j)/(N_j - colsum_j) * Z_j / (1 + rowsum_i - Q(i,j)/N_j), evaluated
    // by hand: 8/75, 8/95, 5/9, 10/23.
    Matrix<Rational> Q(2, 2);
    Q(0, 0) = Rational(1);
    Q(0, 1) = Rational(2);
    Q(1, 0) = Rational(1, 2);
    Q(1, 1) = Rational(1);
    const std::vector<Rational> N{Rational(4), Rational(5)};
    const std::vector<Rational> Z{Rational(1), Rational(2)};

    const Matrix<Rational> D = infer_qmle(Q, N, Z);
    CHECK(D(0, 0) == Rational(8, 75));
    CHECK(D(1, 0) == Rational(8, 95));
    CHECK(D(0, 1) == Rational(5, 9));
    CHECK(D(1, 1) == Rational(10, 23));
}

TEST_CASE("infer_qmle matches MATLAB infer_qmle.m") {
    // Reference from matlab -batch infer_qmle. The computation is a handful of
    // field operations, so double agrees to the last few ulps; 1e-13 relative.
    Matrix<double> Q(2, 2);
    Q(0, 0) = 1.0;
    Q(0, 1) = 2.0;
    Q(1, 0) = 0.5;
    Q(1, 1) = 1.0;
    const Matrix<double> D = infer_qmle(Q, std::vector<double>{4.0, 5.0},
                                        std::vector<double>{1.0, 2.0});
    CHECK(rel(D(0, 0), 0.106666666666667) < 1e-13);
    CHECK(rel(D(1, 0), 0.0842105263157895) < 1e-13);
    CHECK(rel(D(0, 1), 0.555555555555556) < 1e-13);
    CHECK(rel(D(1, 1), 0.434782608695652) < 1e-13);
}

TEST_CASE("infer_qmle rejects a degenerate observation") {
    Matrix<double> Q(1, 1, 2.0);
    // the whole population is in the queue, so no think-time population is left
    CHECK_THROWS_AS(infer_qmle(Q, std::vector<double>{2.0}, std::vector<double>{1.0}),
                    line::NumericError);
    CHECK_THROWS_AS(infer_qmle(Q, std::vector<double>{2.0, 3.0}, std::vector<double>{1.0}),
                    line::InputError);
}

TEST_CASE("infer_compute_ql_at_arrival matches MATLAB and its hand replay") {
    // Three jobs: class 1 at t=0 for 5/2, class 2 at t=1 for 1/2, class 1 at
    // t=2 for 1. Job 1 is still in service when jobs 2 and 3 arrive, job 2 has
    // already left at t=3/2. Exact in rationals: the answers are integers.
    const std::vector<Rational> at{Rational(0), Rational(1), Rational(2)};
    const std::vector<Rational> rt{Rational(5, 2), Rational(1, 2), Rational(1)};
    const std::vector<long> jid{1, 2, 3};
    const std::vector<std::size_t> cls{0, 1, 0};

    const Matrix<Rational> ql = infer_compute_ql_at_arrival(at, jid, rt, jid, cls, 2);
    CHECK(ql(0, 0) == Rational(1));
    CHECK(ql(0, 1) == Rational(0));
    CHECK(ql(1, 0) == Rational(1));
    CHECK(ql(1, 1) == Rational(1));
    CHECK(ql(2, 0) == Rational(2));
    CHECK(ql(2, 1) == Rational(0));
}

TEST_CASE("infer_compute_ql_at_arrival puts a departure before a tied arrival") {
    // Job 1 departs at t=1 exactly when job 2 arrives. The documented rule
    // processes the departure first, so job 2 sees only itself. In rationals
    // the tie is decided by that rule and never by rounding.
    const std::vector<Rational> at{Rational(0), Rational(1)};
    const std::vector<Rational> rt{Rational(1), Rational(1)};
    const std::vector<long> jid{1, 2};
    const std::vector<std::size_t> cls{0, 0};
    const Matrix<Rational> ql = infer_compute_ql_at_arrival(at, jid, rt, jid, cls, 1);
    CHECK(ql(0, 0) == Rational(1));
    CHECK(ql(1, 0) == Rational(1));  // MATLAB QLTIE = [1 1]
}

TEST_CASE("infer_compute_ql_at_arrival conserves the job count") {
    // A longer replay: every recorded queue length is a positive integer, no
    // class count is ever negative, and the last arrival can see no more than
    // the number of jobs admitted so far. Exact assertions in rationals.
    const std::size_t n = 12;
    std::vector<Rational> at, rt;
    std::vector<long> jid;
    std::vector<std::size_t> cls;
    for (std::size_t i = 0; i < n; ++i) {
        at.push_back(Rational(static_cast<long>(i), 3));
        rt.push_back(Rational(1 + static_cast<long>(i % 4), 2));
        jid.push_back(static_cast<long>(n - i));  // ids deliberately out of order
        cls.push_back(i % 3);
    }
    // response times supplied in a different order, matched by id
    std::vector<Rational> rt_shuffled(n);
    std::vector<long> rt_id(n);
    for (std::size_t i = 0; i < n; ++i) {
        rt_shuffled[n - 1 - i] = rt[i];
        rt_id[n - 1 - i] = jid[i];
    }

    const Matrix<Rational> ql = infer_compute_ql_at_arrival(at, jid, rt_shuffled, rt_id, cls, 3);
    for (std::size_t i = 0; i < n; ++i) {
        Rational tot = Rational(0);
        for (std::size_t c = 0; c < 3; ++c) {
            CHECK(ql(i, c) >= Rational(0));
            CHECK(denominator(ql(i, c)) == 1);  // integer counts, exactly
            tot += ql(i, c);
        }
        CHECK(tot >= Rational(1));                          // the arriving job counts itself
        CHECK(tot <= Rational(static_cast<long>(i) + 1));   // and only earlier jobs can be present
        CHECK(ql(i, cls[i]) >= Rational(1));                // its own class holds at least it
    }
}

TEST_CASE("infer_compute_ql_at_arrival rejects an unmatched job id") {
    const std::vector<double> at{0.0, 1.0};
    const std::vector<double> rt{1.0};
    CHECK_THROWS_AS(infer_compute_ql_at_arrival(at, std::vector<long>{1, 2}, rt,
                                                std::vector<long>{1},
                                                std::vector<std::size_t>{0, 0}, 1),
                    line::InputError);
    CHECK_THROWS_AS(infer_compute_ql_at_arrival(at, std::vector<long>{1, 2},
                                                std::vector<double>{1.0, 1.0},
                                                std::vector<long>{1, 2},
                                                std::vector<std::size_t>{0, 5}, 1),
                    line::InputError);
}

TEST_CASE("infer_get_qlen_arrival splits the shared replay per class") {
    // Same three jobs as above, presented per class and with arrival times in
    // milliseconds: class 0 at 0 and 2000 ms, class 1 at 1000 ms. The split
    // must reproduce the pooled replay row for row.
    const std::vector<std::vector<Rational>> at_ms{{Rational(0), Rational(2000)}, {Rational(1000)}};
    const std::vector<std::vector<Rational>> rt{{Rational(5, 2), Rational(1)}, {Rational(1, 2)}};

    const std::vector<Matrix<Rational>> ql = infer_get_qlen_arrival(at_ms, rt);
    REQUIRE(ql.size() == 2);
    REQUIRE(ql[0].rows() == 2);
    REQUIRE(ql[1].rows() == 1);
    // class 0, first sample: only itself
    CHECK(ql[0](0, 0) == Rational(1));
    CHECK(ql[0](0, 1) == Rational(0));
    // class 0, second sample at t=2: itself plus job 1, class 1 already gone
    CHECK(ql[0](1, 0) == Rational(2));
    CHECK(ql[0](1, 1) == Rational(0));
    // class 1 at t=1: job 1 still in service
    CHECK(ql[1](0, 0) == Rational(1));
    CHECK(ql[1](0, 1) == Rational(1));
}

TEST_CASE("infer_rps hand values and MATLAB reference") {
    // rt = [1 2 3 4], classes [0 0 1 1], ql rows [0 0],[1 0],[0 1],[1 1].
    // Class 0: Qbar = [1 2], demand = (1*1 + 2*2)/(1 + 4) = 1.
    // Class 1: Qbar = [2 3], demand = (2*3 + 3*4)/(4 + 9) = 18/13.
    const std::vector<Rational> rt{Rational(1), Rational(2), Rational(3), Rational(4)};
    const std::vector<std::size_t> cls{0, 0, 1, 1};
    Matrix<Rational> ql(4, 2, Rational(0));
    ql(1, 0) = Rational(1);
    ql(2, 1) = Rational(1);
    ql(3, 0) = Rational(1);
    ql(3, 1) = Rational(1);

    const std::vector<Rational> d1 = infer_rps(rt, cls, ql, 1);
    CHECK(d1[0] == Rational(1));
    CHECK(d1[1] == Rational(18, 13));

    // V servers scale the regressor by 1/V, hence the estimate by V exactly.
    const std::vector<Rational> d2 = infer_rps(rt, cls, ql, 2);
    CHECK(d2[0] == Rational(2));
    CHECK(d2[1] == Rational(36, 13));

    // MATLAB lsqnonneg agrees with the closed form to full double precision.
    const std::vector<double> rtd{1.0, 2.0, 3.0, 4.0};
    Matrix<double> qld(4, 2, 0.0);
    qld(1, 0) = 1.0;
    qld(2, 1) = 1.0;
    qld(3, 0) = 1.0;
    qld(3, 1) = 1.0;
    const std::vector<double> dd = infer_rps(rtd, cls, qld, 1);
    CHECK(rel(dd[0], 1.0) < 1e-14);
    CHECK(rel(dd[1], 1.38461538461538) < 1e-13);
}

TEST_CASE("infer_rps respects the non-negativity bound") {
    // Response times of zero drive the unconstrained fit to zero, and it is
    // returned exactly rather than as a tiny negative number.
    const std::vector<Rational> rt{Rational(0), Rational(0)};
    const std::vector<std::size_t> cls{0, 0};
    const Matrix<Rational> ql(2, 1, Rational(1));
    const std::vector<Rational> d = infer_rps(rt, cls, ql, 1);
    CHECK(d[0] == Rational(0));

    CHECK_THROWS_AS(infer_rps(rt, cls, ql, 0), line::InputError);
    CHECK_THROWS_AS(infer_rps(rt, std::vector<std::size_t>{1, 1}, ql, 1), line::InputError);
}

TEST_CASE("infer_lqn_jacobian is exact on an affine map") {
    // For h(a) = M a + b the forward difference has no truncation error, so
    // the returned matrix must be M itself, entry for entry, in rationals.
    Matrix<Rational> M(3, 2);
    M(0, 0) = Rational(1, 2);
    M(0, 1) = Rational(-3);
    M(1, 0) = Rational(7, 5);
    M(1, 1) = Rational(0);
    M(2, 0) = Rational(0);
    M(2, 1) = Rational(11, 3);
    const std::vector<Rational> b{Rational(1), Rational(-2), Rational(4)};

    const std::function<std::vector<Rational>(const std::vector<Rational>&)> h =
        [&](const std::vector<Rational>& a) {
            std::vector<Rational> z = b;
            for (std::size_t k = 0; k < 3; ++k)
                for (std::size_t i = 0; i < 2; ++i) z[k] += M(k, i) * a[i];
            return z;
        };

    const std::vector<Rational> a{Rational(2), Rational(-1, 3)};
    const auto r = infer_lqn_jacobian(h, a);
    for (std::size_t k = 0; k < 3; ++k) {
        CHECK(r.h0[k] == b[k] + M(k, 0) * a[0] + M(k, 1) * a[1]);
        for (std::size_t i = 0; i < 2; ++i) CHECK(r.H(k, i) == M(k, i));
    }
}

TEST_CASE("infer_lqn_jacobian returns the exact difference quotient of a product") {
    // h(a) = a0 a1. The forward difference in coordinate 0 is exactly a1 and
    // in coordinate 1 exactly a0, whatever the step: the truncation term of a
    // bilinear map vanishes in the first argument. That pins the step down
    // too, so the test also verifies d_i = fd_step max(|a_i|, fd_floor).
    const std::function<std::vector<Rational>(const std::vector<Rational>&)> h =
        [](const std::vector<Rational>& a) { return std::vector<Rational>{a[0] * a[1]}; };
    const std::vector<Rational> a{Rational(3), Rational(5, 2)};
    const auto r = infer_lqn_jacobian(h, a, 1.0 / 1024.0, 1.0 / 65536.0);
    CHECK(r.h0[0] == Rational(15, 2));
    CHECK(r.H(0, 0) == a[1]);
    CHECK(r.H(0, 1) == a[0]);

    // At a = 0 the floor takes over, and the quotient of a quadratic is the
    // step itself: (0 + d)^2 / d = d = fd_step * fd_floor.
    const std::function<std::vector<Rational>(const std::vector<Rational>&)> q =
        [](const std::vector<Rational>& x) { return std::vector<Rational>{x[0] * x[0]}; };
    const auto r2 = infer_lqn_jacobian(q, std::vector<Rational>{Rational(0)}, 1.0 / 1024.0,
                                       1.0 / 65536.0);
    CHECK(r2.H(0, 0) == Rational(1, 1024) * Rational(1, 65536));

    CHECK_THROWS_AS(infer_lqn_jacobian(q, std::vector<Rational>{}), line::InputError);
}

TEST_CASE("infer_lqn_jacobian at high precision converges to the derivative") {
    // A genuinely nonlinear map: the forward difference of exp at 1 with the
    // default step is off by about step/2 * exp(1), which is the truncation
    // error of the formula and not of the arithmetic.
    const std::function<std::vector<Real50>(const std::vector<Real50>&)> h =
        [](const std::vector<Real50>& a) {
            const Real50 v = exp(a[0]);
            return std::vector<Real50>{v};
        };
    const auto r = infer_lqn_jacobian(h, std::vector<Real50>{Real50(1)}, 1e-3, 1e-6);
    const double e = std::exp(1.0);
    CHECK(std::fabs(static_cast<double>(r.H(0, 0)) - e) < 2e-3);
    CHECK(std::fabs(static_cast<double>(r.H(0, 0)) - e - 0.5e-3 * e) < 1e-6);
}

TEST_CASE("infer_lqn_findbyname returns the first match, exactly as MATLAB") {
    // MATLAB: c={struct('name','P1'),struct('name','T1'),struct('name','P1')};
    //         infer_lqn_findbyname(c,'T1')  -> the second element
    //         infer_lqn_findbyname(c,'P1')  -> the FIRST of the two
    //         infer_lqn_findbyname(c,'zzz') -> []
    const std::vector<std::string> names{"P1", "T1", "P1"};
    CHECK(line::infer::infer_lqn_findbyname(names, "T1") == 1u);
    CHECK(line::infer::infer_lqn_findbyname(names, "P1") == 0u);
    CHECK(line::infer::infer_lqn_findbyname(names, "zzz") == line::infer::INFER_LQN_NOT_FOUND);
    CHECK(line::infer::infer_lqn_findbyname(std::vector<std::string>(), "P1") ==
          line::infer::INFER_LQN_NOT_FOUND);
}

TEST_CASE("infer_lqn_getobs selects the specified metrics") {
    // MATLAB:
    //   names={'P1','T1','E1','A1'};
    //   metrics.QLen=[0.1 0.2 0.3 0.4]; metrics.Util=[0.5 0.6 0.7 0.8];
    //   metrics.RespT=[1.5 2.5 3.5 4.5]; metrics.Tput=[10 20 30 40];
    //   obsSpec(1)=struct('metric','Util','name','P1');
    //   obsSpec(2)=struct('metric','RespT','name','E1');
    //   obsSpec(3)=struct('metric','Tput','name','T1');
    //   obsSpec(4)=struct('metric','QLen','name','A1');
    //   infer_lqn_getobs(names,metrics,obsSpec)' -> [0.5 3.5 20 0.4]
    const std::vector<std::string> names{"P1", "T1", "E1", "A1"};
    line::infer::LqnMetrics<Rational> m;
    m.QLen = {Rational(1, 10), Rational(2, 10), Rational(3, 10), Rational(4, 10)};
    m.Util = {Rational(5, 10), Rational(6, 10), Rational(7, 10), Rational(8, 10)};
    m.RespT = {Rational(3, 2), Rational(5, 2), Rational(7, 2), Rational(9, 2)};
    m.Tput = {Rational(10), Rational(20), Rational(30), Rational(40)};
    const std::vector<line::infer::LqnObsSpec> spec{
        {line::infer::LqnMetric::Util, "P1"},
        {line::infer::LqnMetric::RespT, "E1"},
        {line::infer::LqnMetric::Tput, "T1"},
        {line::infer::LqnMetric::QLen, "A1"}};

    const std::vector<Rational> z = line::infer::infer_lqn_getobs(names, m, spec);
    REQUIRE(z.size() == 4u);
    CHECK(z[0] == Rational(1, 2));
    CHECK(z[1] == Rational(7, 2));
    CHECK(z[2] == Rational(20));
    CHECK(z[3] == Rational(2, 5));

    // MATLAB raises 'Element ''nope'' not found in the LQN.'
    const std::vector<line::infer::LqnObsSpec> bad{{line::infer::LqnMetric::Util, "nope"}};
    CHECK_THROWS_AS(line::infer::infer_lqn_getobs(names, m, bad), line::InputError);
}

TEST_CASE("infer_lqn_ekf against MATLAB on an analytic observation map") {
    // MATLAB:
    //   hfun = @(a) [a(1)*a(2); a(1) + a(2)^2];
    //   a0=[1;1]; P0=0.1*eye(2); Q=0.01*eye(2); R=0.05*eye(2);
    //   Z=[2.10 2.30 2.50; 3.05 3.40 3.60];
    //   [ahat,info]=infer_lqn_ekf(hfun,a0,P0,Z,Q,R,struct('aTrue',[1.5;1.4]));
    const std::function<std::vector<double>(const std::vector<double>&)> h =
        [](const std::vector<double>& a) {
            return std::vector<double>{a[0] * a[1], a[0] + a[1] * a[1]};
        };
    const std::vector<double> a0{1.0, 1.0};
    Matrix<double> P0(2, 2, 0.0);
    P0(0, 0) = 0.1;
    P0(1, 1) = 0.1;
    Matrix<double> Q(2, 2, 0.0);
    Q(0, 0) = 0.01;
    Q(1, 1) = 0.01;
    Matrix<double> R(2, 2, 0.0);
    R(0, 0) = 0.05;
    R(1, 1) = 0.05;
    Matrix<double> Z(2, 3, 0.0);
    Z(0, 0) = 2.10;
    Z(0, 1) = 2.30;
    Z(0, 2) = 2.50;
    Z(1, 0) = 3.05;
    Z(1, 1) = 3.40;
    Z(1, 2) = 3.60;
    line::infer::EkfOptions<double> opts;
    opts.a_true = std::vector<double>{1.5, 1.4};

    const line::infer::EkfResult<double> r = line::infer::infer_lqn_ekf(h, a0, P0, Z, Q, R, opts);

    // ahat, column-major as MATLAB printed it
    CHECK(rel(r.ahat(0, 0), 1.4848367291899522) < 1e-12);
    CHECK(rel(r.ahat(1, 0), 1.3198754449084507) < 1e-12);
    CHECK(rel(r.ahat(0, 1), 1.6132073762652714) < 1e-12);
    CHECK(rel(r.ahat(1, 1), 1.3400897899131465) < 1e-12);
    CHECK(rel(r.ahat(0, 2), 1.7203877722413965) < 1e-12);
    CHECK(rel(r.ahat(1, 2), 1.3716893324633239) < 1e-12);

    // zpred: the first step predicts h(a0) = [1; 2] exactly
    CHECK(rel(r.zpred(0, 0), 1.0) < 1e-15);
    CHECK(rel(r.zpred(1, 0), 2.0) < 1e-15);
    CHECK(rel(r.zpred(0, 1), 1.959799538555997) < 1e-12);
    CHECK(rel(r.zpred(1, 1), 3.2269079192622327) < 1e-12);
    CHECK(rel(r.zpred(0, 2), 2.1618427339456661) < 1e-12);
    CHECK(rel(r.zpred(1, 2), 3.4090480212947325) < 1e-12);

    // innovations
    CHECK(rel(r.e(0, 0), 1.1000000000000001) < 1e-12);
    CHECK(rel(r.e(1, 0), 1.0499999999999998) < 1e-12);
    CHECK(rel(r.e(0, 2), 0.33815726605433394) < 1e-12);
    CHECK(rel(r.e(1, 2), 0.19095197870526759) < 1e-12);

    // final covariance, symmetric by construction
    CHECK(rel(r.P(0, 0), 0.037268760977297644) < 1e-11);
    CHECK(rel(r.P(0, 1), -0.017631424415920943) < 1e-11);
    CHECK(r.P(0, 1) == r.P(1, 0));
    CHECK(rel(r.P(1, 1), 0.012232513480750965) < 1e-11);

    CHECK(rel(r.Er, 0.65942022731305927) < 1e-12);
    REQUIRE(r.has_Ea);
    CHECK(rel(r.Ea, 0.10986907092360211) < 1e-12);
    CHECK(r.Phist.size() == 3u);
}

TEST_CASE("infer_lqn_ekf recovers a linear parameter and rejects bad shapes") {
    // With h linear the EKF is the exact Kalman filter, so with noiseless
    // measurements of an observable pair the estimate must converge to the
    // truth. h(a) = [a0 + 2 a1; 3 a0 - a1], a = [2; 5] gives z = [12; 1].
    const std::function<std::vector<double>(const std::vector<double>&)> h =
        [](const std::vector<double>& a) {
            return std::vector<double>{a[0] + 2.0 * a[1], 3.0 * a[0] - a[1]};
        };
    const std::size_t nsteps = 40;
    Matrix<double> Z(2, nsteps, 0.0);
    for (std::size_t k = 0; k < nsteps; ++k) {
        Z(0, k) = 12.0;
        Z(1, k) = 1.0;
    }
    Matrix<double> P0(2, 2, 0.0), Q(2, 2, 0.0), R(2, 2, 0.0);
    P0(0, 0) = P0(1, 1) = 1.0;
    Q(0, 0) = Q(1, 1) = 1e-6;
    R(0, 0) = R(1, 1) = 1e-3;
    const line::infer::EkfResult<double> r =
        line::infer::infer_lqn_ekf(h, std::vector<double>{1.0, 1.0}, P0, Z, Q, R);
    // MATLAB, same setup:
    //   hfun=@(a)[a(1)+2*a(2); 3*a(1)-a(2)]; Z=repmat([12;1],1,40);
    //   [ahat,info]=infer_lqn_ekf(hfun,[1;1],eye(2),Z,1e-6*eye(2),1e-3*eye(2));
    //   ahat(:,end) -> 1.9999985129014279, 4.999992695927439
    //   info.e(1,end) -> 1.7262250169736149e-05
    // The residual 1.5e-6 is not a defect of either implementation: with
    // process noise Q the covariance has a nonzero fixed point, so the gain
    // never reaches zero and the estimate keeps a bias of order sqrt(Q/R).
    CHECK(rel(r.ahat(0, nsteps - 1), 1.9999985129014279) < 1e-10);
    CHECK(rel(r.ahat(1, nsteps - 1), 4.999992695927439) < 1e-10);
    CHECK(rel(r.e(0, nsteps - 1), 1.7262250169736149e-05) < 1e-8);
    CHECK(!r.has_Ea);
    // the innovation must shrink monotonically in this noiseless linear case
    CHECK(std::fabs(r.e(0, nsteps - 1)) < std::fabs(r.e(0, 0)));

    Matrix<double> Rbad(3, 3, 0.0);
    CHECK_THROWS_AS(line::infer::infer_lqn_ekf(h, std::vector<double>{1.0, 1.0}, P0, Z, Q, Rbad),
                    line::InputError);
    CHECK_THROWS_AS(line::infer::infer_lqn_ekf(h, std::vector<double>(), P0, Z, Q, R),
                    line::InputError);
}
