/*
 * Copyright (c) 2012-2026, QORE Lab, Imperial College London
 * All rights reserved.
 */

package jline.lang.state;

import jline.GlobalConstants;
import jline.io.Ret;
import jline.lang.NetworkStruct;
import jline.lang.constant.EventType;
import jline.lang.nodeparam.JoinNodeParam;
import jline.util.matrix.Matrix;

import java.io.Serializable;

/**
 * Event handler for Join stations on FJ tag-augmented structs (see
 * ModelAdapter.fjtag). The join state is a plain per-class count vector
 * [n_1..n_R] of buffered jobs: auxiliary-class entries count the sibling
 * tasks waiting for synchronization.
 *
 * ARV (passive): buffer the arriving job/sibling. DEP in an original
 * class r (active, immediate): enabled when a plain class-r job is
 * buffered, or when some tag t has the full required sibling multiset
 * present (identity matching by tag). The firing consumes the siblings of
 * the LOWEST complete tag and lets one class-r job depart; the
 * r-to-destination move is the regular sync pairing generated by
 * refreshSync from the join routing. Auxiliary classes never depart
 * individually.
 */
public class AfterEventJoin implements Serializable {

    static Ret.EventResult afterEventJoin(NetworkStruct sn, int ind, Matrix inspace, EventType event, int jobClass, boolean isSimulation) {
        int R = sn.nclasses;
        int nRows = inspace.getNumRows();
        int nCols = inspace.getNumCols();

        Matrix outspace = new Matrix(0, 0);
        Matrix outrate = new Matrix(0, 0);
        Matrix outprob = new Matrix(1, 1);
        outprob.set(0, 0, 1.0);

        // per-class counts are the last R columns
        Matrix n = new Matrix(nRows, R);
        for (int row = 0; row < nRows; row++) {
            for (int r = 0; r < R; r++) {
                n.set(row, r, inspace.get(row, nCols - R + r));
            }
        }

        if (event == EventType.ARV) {
            for (int row = 0; row < nRows; row++) {
                n.set(row, jobClass, n.get(row, jobClass) + 1);
            }
            outspace = n;
            outrate = new Matrix(nRows, 1);
            outrate.ones();
            outrate.scaleEq(-1); // passive action, rate is unspecified
            outprob = new Matrix(nRows, 1);
            outprob.ones();
            return new Ret.EventResult(outspace, outrate, outprob);
        }

        if (event == EventType.DEP) {
            JoinNodeParam jnp = (JoinNodeParam) sn.nodeparam.get(sn.nodes.get(ind));
            // auxiliary sibling classes never depart individually
            if (jnp != null && jnp.fjOrigclasses != null) {
                for (int rr : jnp.fjOrigclasses) {
                    Matrix auxm = jnp.fjAuxmatrix.get(rr);
                    if (auxm != null) {
                        for (int b = 0; b < auxm.getNumRows(); b++) {
                            for (int t = 0; t < auxm.getNumCols(); t++) {
                                if ((int) auxm.get(b, t) == jobClass) {
                                    return new Ret.EventResult(new Matrix(0, 0), new Matrix(0, 0), outprob);
                                }
                            }
                        }
                    }
                }
            }

            java.util.List<double[]> outRows = new java.util.ArrayList<double[]>();
            for (int row = 0; row < nRows; row++) {
                double[] nrow = new double[R];
                for (int r = 0; r < R; r++) {
                    nrow[r] = n.get(row, r);
                }
                if (nrow[jobClass] > 0) {
                    // plain (non-forked) job buffered in the departing class
                    nrow[jobClass] -= 1;
                    outRows.add(nrow);
                } else if (jnp != null && jnp.fjOrigclasses != null && jnp.fjOrigclasses.contains(jobClass)) {
                    Matrix auxm = jnp.fjAuxmatrix.get(jobClass); // B x T
                    Matrix req = jnp.fjRequired.get(jobClass);   // B x 1
                    if (auxm == null) {
                        continue;
                    }
                    int B = auxm.getNumRows();
                    int T = auxm.getNumCols();
                    int tstar = -1;
                    for (int t = 0; t < T && tstar < 0; t++) {
                        boolean complete = true;
                        for (int b = 0; b < B; b++) {
                            if (nrow[(int) auxm.get(b, t)] < req.get(b, 0)) {
                                complete = false;
                                break;
                            }
                        }
                        if (complete) {
                            tstar = t; // lowest complete tag, canonical consumption
                        }
                    }
                    if (tstar >= 0) {
                        for (int b = 0; b < B; b++) {
                            nrow[(int) auxm.get(b, tstar)] -= req.get(b, 0);
                        }
                        outRows.add(nrow);
                    }
                }
            }
            if (!outRows.isEmpty()) {
                outspace = new Matrix(outRows.size(), R);
                for (int i = 0; i < outRows.size(); i++) {
                    for (int r = 0; r < R; r++) {
                        outspace.set(i, r, outRows.get(i)[r]);
                    }
                }
                outrate = new Matrix(outRows.size(), 1);
                outrate.fill(GlobalConstants.Immediate);
                outprob = new Matrix(outRows.size(), 1);
                outprob.ones();
            }
        }

        return new Ret.EventResult(outspace, outrate, outprob);
    }
}
