/*
 * Copyright (c) 2012-2026, QORE Lab, Imperial College London
 * All rights reserved.
 */

package jline.io.tikz;

import jline.lang.Network;
import jline.lang.Environment;

/**
 * Utility to generate all tutorial images for the LINE documentation website.
 * Generates PNG images from network models using TikZ export.
 */
public class GenerateTutorialImages {

    public static void main(String[] args) {
        // Output directory (doc/img/)
        // Determine absolute path to doc/img/
        String currentDir = System.getProperty("user.dir");
        String imgDir;
        if (currentDir.endsWith("/jar")) {
            imgDir = currentDir.replace("/jar", "/doc/img/");
        } else {
            imgDir = currentDir + "/doc/img/";
        }
        int dpi = 200;  // DPI for PNG export

        System.out.println("Generating tutorial images to: " + imgDir);

        int successCount = 0;
        int failureCount = 0;

        // Tutorial 1: M/M/1 basics
        try {
            System.out.println("Generating tut01_mm1_network.png...");
            Network tut01 = jline.examples.java.GettingStarted.tut01_mm1_basics();
            tut01.tikzExportPNG(imgDir + "tut01_mm1_network", dpi);
            System.out.println("  [OK] tut01_mm1_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut01: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 2: M/G/1 multiclass
        try {
            System.out.println("Generating tut02_mg1_network.png...");
            Network tut02 = jline.examples.java.GettingStarted.tut02_mg1_multiclass_solvers();
            tut02.tikzExportPNG(imgDir + "tut02_mg1_network", dpi);
            System.out.println("  [OK] tut02_mg1_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut02: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 3: Repairmen (closed network)
        try {
            System.out.println("Generating tut03_repairmen_network.png...");
            Network tut03 = jline.examples.java.GettingStarted.tut03_repairmen();
            tut03.tikzExportPNG(imgDir + "tut03_repairmen_network", dpi);
            System.out.println("  [OK] tut03_repairmen_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut03: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 4: Load balancing with routing
        try {
            System.out.println("Generating tut04_lb_routing_network.png...");
            Network tut04 = jline.examples.java.GettingStarted.tut04_lb_routing();
            tut04.tikzExportPNG(imgDir + "tut04_lb_routing_network", dpi);
            System.out.println("  [OK] tut04_lb_routing_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut04: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 5: Re-entrant line (completes flag)
        // Use hideAutoGeneratedNodes to show a clean single-queue diagram with self-loop
        try {
            System.out.println("Generating tut05_reentrant_network.png...");
            Network tut05 = jline.examples.java.GettingStarted.tut05_completes_flag();
            TikZOptions options = new TikZOptions().setHideAutoGeneratedNodes(true);
            TikZExporter exporter = new TikZExporter(tut05, options);
            exporter.exportToPNG(imgDir + "tut05_reentrant_network.png", dpi);
            System.out.println("  [OK] tut05_reentrant_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut05: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 7: Response time distribution (closed network)
        try {
            System.out.println("Generating tut07_respt_network.png...");
            Network tut07 = jline.examples.java.GettingStarted.tut07_respt_cdf();
            tut07.tikzExportPNG(imgDir + "tut07_respt_network", dpi);
            System.out.println("  [OK] tut07_respt_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut07: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 8: Optimization / load balancing
        try {
            System.out.println("Generating tut08_optimization_network.png...");
            Network tut08 = jline.examples.java.GettingStarted.tut08_opt_load_balancing();
            tut08.tikzExportPNG(imgDir + "tut08_optimization_network", dpi);
            System.out.println("  [OK] tut08_optimization_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut08: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 6: Cache with LRU and Zipf
        // Use hideAutoGeneratedNodes to hide the auto-generated ClassSwitch node
        try {
            System.out.println("Generating tut06_cache_network.png...");
            Network tut06 = jline.examples.java.GettingStarted.tut06_cache_lru_zipf();
            TikZOptions tut06Options = new TikZOptions().setHideAutoGeneratedNodes(true);
            TikZExporter tut06Exporter = new TikZExporter(tut06, tut06Options);
            tut06Exporter.exportToPNG(imgDir + "tut06_cache_network.png", dpi);
            System.out.println("  [OK] tut06_cache_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut06: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 10: Layered queueing network (LQN)
        try {
            System.out.println("Generating tut10_lqn_network.png...");
            jline.lang.layered.LayeredNetwork tut10 = jline.examples.java.GettingStarted.tut10_lqn_basics();
            // LQN models need special handling - use the plotGraph visualization
            // For now, we skip PNG export as LayeredNetwork doesn't have tikzExportPNG
            // The image should be generated manually using MATLAB's plot() function
            System.out.println("  [WARN] tut10_lqn_network.png skipped - LayeredNetwork TikZ export not yet implemented");
            System.out.println("    Use MATLAB to generate: model.plot(); print('tut10_lqn_network.png', '-dpng', '-r150');");
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut10: " + e.getMessage());
            failureCount++;
        }

        // Tutorial 11: Random environment (network + Markov chain)
        try {
            System.out.println("Generating tut11_env_network.png...");
            Environment env11 = jline.examples.java.GettingStarted.tut11_random_env();
            // Export the first stage (Fast mode) with Markov chain showing environment transitions
            Network tut11 = env11.getModel(0);

            // Define environment stages and transition rates
            String[] stageNames = {"Fast", "Slow"};
            double[][] transitionRates = {
                {0.0, 0.5},  // Fast -> Slow at rate 0.5
                {1.0, 0.0}   // Slow -> Fast at rate 1.0
            };

            TikZExporter exporter = new TikZExporter(tut11);
            exporter.exportEnvironmentToPNG(imgDir + "tut11_env_network.png", dpi, stageNames, transitionRates);
            System.out.println("  [OK] tut11_env_network.png generated");
            successCount++;
        } catch (Exception e) {
            System.err.println("  [FAIL] Failed to generate tut11: " + e.getMessage());
            e.printStackTrace();
            failureCount++;
        }

        System.out.println("\n==== Summary ====");
        System.out.println("Successfully generated: " + successCount + " images");
        System.out.println("Failed: " + failureCount + " images");
        System.out.println("Images saved to: " + imgDir);

        if (failureCount > 0) {
            System.exit(1);
        }
    }
}
