package jline.opt;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import jline.opt.solver.de.DifferentialEvolution;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Validates that the Java {@link DifferentialEvolution} engine reproduces
 * scipy's {@code differential_evolution} trajectory bit-for-bit for a fixed
 * seed, against fixtures generated by {@code gen_golden.py} on the pure-math
 * objective {@code f(x)=sum((x-0.3)^2)}. This is the end-to-end RNG parity gate
 * for the optimizer, independent of any LINE model.
 */
public class DETrajectoryTest {

    private JsonObject loadGolden() throws Exception {
        InputStream in = getClass().getClassLoader()
                .getResourceAsStream("opt/opt_rng_golden.json");
        assertTrue(in != null, "opt/opt_rng_golden.json resource missing");
        InputStreamReader r = new InputStreamReader(in, StandardCharsets.UTF_8);
        return JsonParser.parseReader(r).getAsJsonObject();
    }

    private DifferentialEvolution.Objective sphere() {
        return new DifferentialEvolution.Objective() {
            public double evaluate(double[] x) {
                double s = 0.0;
                for (double v : x) {
                    s += (v - 0.3) * (v - 0.3);
                }
                return s;
            }
        };
    }

    private void checkSeed(JsonObject g, int seed) {
        double[] low = {-1, -1, 0};
        double[] high = {1, 1, 2};
        DifferentialEvolution de = new DifferentialEvolution(
                sphere(), low, high, "best1bin", 5, 8,
                0.5, 1.0, 0.7, 0.0, seed);
        DifferentialEvolution.Result res = de.solve();

        JsonObject e = g.getAsJsonObject(Integer.toString(seed));
        JsonArray ex = e.getAsJsonArray("x");
        for (int j = 0; j < 3; j++) {
            assertEquals(ex.get(j).getAsDouble(), res.x[j], 1e-12,
                    "seed " + seed + " x[" + j + "]");
        }
        assertEquals(e.get("fun").getAsDouble(), res.fun, 1e-12,
                "seed " + seed + " fun");

        JsonArray gens = e.getAsJsonArray("best_per_gen");
        List<double[]> got = res.bestPerGen;
        assertEquals(gens.size(), got.size(), "seed " + seed + " num generations");
        for (int gi = 0; gi < gens.size(); gi++) {
            JsonArray row = gens.get(gi).getAsJsonArray();
            for (int j = 0; j < row.size(); j++) {
                assertEquals(row.get(j).getAsDouble(), got.get(gi)[j], 1e-12,
                        "seed " + seed + " gen " + gi + " x[" + j + "]");
            }
        }
    }

    @Test
    public void testTrajectorySeed42() throws Exception {
        checkSeed(loadGolden().getAsJsonObject("de_trajectory"), 42);
    }

    @Test
    public void testTrajectorySeed7() throws Exception {
        checkSeed(loadGolden().getAsJsonObject("de_trajectory"), 7);
    }
}
