package jline.opt;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import jline.opt.solver.de.NumpyRandomState;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Hard gate for cross-codebase differential-evolution parity: asserts the Java
 * {@link NumpyRandomState} reproduces numpy's legacy RandomState draws
 * bit-for-bit against fixtures generated by {@code gen_golden.py}
 * (numpy 2.3.5). If this fails, DE trajectories will diverge from native
 * Python, so nothing downstream can be trusted.
 */
public class RandomStateGoldenTest {

    private static final int[] SEEDS = {0, 1, 42, 12345};

    private JsonObject loadGolden() throws Exception {
        InputStream in = getClass().getClassLoader()
                .getResourceAsStream("opt/opt_rng_golden.json");
        assertTrue(in != null, "opt/opt_rng_golden.json resource missing");
        InputStreamReader r = new InputStreamReader(in, StandardCharsets.UTF_8);
        return JsonParser.parseReader(r).getAsJsonObject();
    }

    @Test
    public void testSeedState() throws Exception {
        JsonObject g = loadGolden().getAsJsonObject("seed_state");
        for (int seed : SEEDS) {
            NumpyRandomState rs = new NumpyRandomState(seed);
            int[] key = rs.getGenerator().getStateKey();
            JsonObject e = g.getAsJsonObject(Integer.toString(seed));
            JsonArray first8 = e.getAsJsonArray("first8");
            for (int i = 0; i < 8; i++) {
                assertEquals(first8.get(i).getAsLong(), key[i] & 0xFFFFFFFFL,
                        "seed " + seed + " key[" + i + "]");
            }
            JsonArray last4 = e.getAsJsonArray("last4");
            for (int i = 0; i < 4; i++) {
                assertEquals(last4.get(i).getAsLong(), key[620 + i] & 0xFFFFFFFFL,
                        "seed " + seed + " key[" + (620 + i) + "]");
            }
        }
    }

    @Test
    public void testRandomSample() throws Exception {
        JsonObject g = loadGolden().getAsJsonObject("random_sample");
        for (int seed : SEEDS) {
            NumpyRandomState rs = new NumpyRandomState(seed);
            JsonArray exp = g.getAsJsonArray(Integer.toString(seed));
            for (int i = 0; i < exp.size(); i++) {
                double got = rs.randomSample();
                assertEquals(exp.get(i).getAsDouble(), got, 0.0,
                        "seed " + seed + " random_sample[" + i + "]");
            }
        }
    }

    @Test
    public void testRandint() throws Exception {
        JsonObject g = loadGolden().getAsJsonObject("randint");
        int[] ks = {2, 3, 5, 10, 16, 17, 100, 1000, 7, 13, 64, 65};
        for (int seed : SEEDS) {
            NumpyRandomState rs = new NumpyRandomState(seed);
            JsonArray exp = g.getAsJsonArray(Integer.toString(seed));
            for (int i = 0; i < ks.length; i++) {
                long got = rs.randint(0, ks[i]);
                assertEquals(exp.get(i).getAsLong(), got,
                        "seed " + seed + " randint(0," + ks[i] + ")");
            }
        }
    }

    @Test
    public void testShuffle() throws Exception {
        JsonObject g = loadGolden().getAsJsonObject("shuffle");
        int[] ns = {2, 3, 4, 5, 7, 10, 17};
        for (int seed : SEEDS) {
            NumpyRandomState rs = new NumpyRandomState(seed);
            JsonObject exp = g.getAsJsonObject(Integer.toString(seed));
            for (int n : ns) {
                int[] arr = new int[n];
                for (int i = 0; i < n; i++) {
                    arr[i] = i;
                }
                rs.shuffle(arr);
                JsonArray e = exp.getAsJsonArray(Integer.toString(n));
                for (int i = 0; i < n; i++) {
                    assertEquals(e.get(i).getAsInt(), arr[i],
                            "seed " + seed + " shuffle(" + n + ")[" + i + "]");
                }
            }
        }
    }

    @Test
    public void testPermutation() throws Exception {
        JsonObject g = loadGolden().getAsJsonObject("permutation");
        int[] ns = {3, 5, 7, 10};
        for (int seed : SEEDS) {
            NumpyRandomState rs = new NumpyRandomState(seed);
            JsonObject exp = g.getAsJsonObject(Integer.toString(seed));
            for (int n : ns) {
                int[] p = rs.permutation(n);
                JsonArray e = exp.getAsJsonArray(Integer.toString(n));
                for (int i = 0; i < n; i++) {
                    assertEquals(e.get(i).getAsInt(), p[i],
                            "seed " + seed + " permutation(" + n + ")[" + i + "]");
                }
            }
        }
    }

    @Test
    public void testUniformDither() throws Exception {
        JsonObject g = loadGolden().getAsJsonObject("uniform_dither");
        for (int seed : SEEDS) {
            NumpyRandomState rs = new NumpyRandomState(seed);
            JsonArray exp = g.getAsJsonArray(Integer.toString(seed));
            for (int i = 0; i < exp.size(); i++) {
                double got = rs.uniform(0.5, 1.0);
                assertEquals(exp.get(i).getAsDouble(), got, 0.0,
                        "seed " + seed + " uniform_dither[" + i + "]");
            }
        }
    }

    @Test
    public void testUniformGrid() throws Exception {
        JsonObject g = loadGolden().getAsJsonObject("uniform_grid");
        for (int seed : SEEDS) {
            NumpyRandomState rs = new NumpyRandomState(seed);
            JsonObject e = g.getAsJsonObject(Integer.toString(seed));
            JsonArray shape = e.getAsJsonArray("shape");
            int total = shape.get(0).getAsInt() * shape.get(1).getAsInt();
            double[] flat = rs.uniform(total);
            JsonArray expFlat = e.getAsJsonArray("flat");
            for (int i = 0; i < total; i++) {
                assertEquals(expFlat.get(i).getAsDouble(), flat[i], 0.0,
                        "seed " + seed + " uniform_grid[" + i + "]");
            }
        }
    }
}
