function varargout = LQN2MATLAB(varargin)
% LQN2MATLAB Generate the MATLAB script of a LayeredNetwork, or load a .lqnx file.
%
% GENERATOR FORM (a LayeredNetwork as first argument):
%
%   LQN2MATLAB(MODEL)
%   LQN2MATLAB(MODEL, MODELNAME)
%   LQN2MATLAB(MODEL, MODELNAME, FID)
%
% writes to FID a MATLAB script that rebuilds MODEL in a variable named
% `model`, by the same constructors a user would write (Processor, Task,
% CacheTask, SetupTask, Entry, ItemEntry, Activity, ActivityPrecedence). FID
% defaults to 1 (standard output); a char or string FID is a file name, which
% is opened for writing and closed on return. MODELNAME defaults to
% MODEL.getName(). The script reads the model OBJECTS, not the struct, so
% everything the objects carry is re-declared exactly: numeric values are
% printed at the shortest spelling that reads back bit for bit, and the
% hosts, tasks, entries and activities are declared in model order so the
% regenerated model has the same LayeredNetworkStruct indexing.
%
% This is the layered twin of QN2MATLAB, and LQN2JAVA is its Java twin.
%
% LOADER FORM (a file name as first argument), kept for backward
% compatibility; LayeredNetwork.parseXML(FILENAME) is the preferred spelling:
%
%   MODEL = LQN2MATLAB(FILENAME)
%   MODEL = LQN2MATLAB(FILENAME, MODELNAME)
%
% parses a .lqnx/.xml layered model and, when MODELNAME is given, renames it.
%
% See also QN2MATLAB, LQN2JAVA, LINE2MATLAB, LayeredNetwork.parseXML

% Copyright (c) 2012-2026, Imperial College London
% All rights reserved.

if nargin < 1
    line_error(mfilename, 'LQN2MATLAB requires a LayeredNetwork or a file name.');
end
first = varargin{1};
if isa(first, 'LayeredNetwork')
    lqn2matlab_generate(varargin{:});
    if nargout > 0
        varargout{1} = first;
    end
elseif ischar(first) || isstring(first)
    varargout{1} = lqn2matlab_load(varargin{:});
else
    line_error(mfilename, sprintf(['LQN2MATLAB expects a LayeredNetwork (code generation) ', ...
        'or a .lqnx/.xml file name (loading), got a %s.'], class(first)));
end
end


function model = lqn2matlab_load(filename, modelName)
% MODEL = LQN2MATLAB_LOAD(FILENAME, MODELNAME) the legacy loader form
filename = char(filename);
[~,~,fext] = fileparts(filename);
switch lower(fext)
    case {'.lqnx','.xml'}
        model = LayeredNetwork.parseXML(filename, false);
        if nargin < 2 || isempty(modelName)
            [~, modelName] = fileparts(filename); % parseXML names the model after the full path
        end
        model.setName(char(modelName));
    otherwise
        line_error(mfilename, 'File extension must be .lqnx or .xml');
end
end


function lqn2matlab_generate(model, modelName, fid)
% LQN2MATLAB_GENERATE(MODEL, MODELNAME, FID) writes the script
if nargin < 2 || isempty(modelName)
    modelName = model.getName();
end
if nargin < 3 || isempty(fid)
    fid = 1;
end
ownsFid = false;
if ischar(fid) || isstring(fid)
    fid = fopen(char(fid), 'w');
    if fid < 0
        line_error(mfilename, 'Cannot open the output file for writing.');
    end
    ownsFid = true;
end
cleanup = onCleanup(@() closeIfOwned(fid, ownsFid)); %#ok<NASGU>

hosts = model.hosts;
tasks = model.tasks;
entries = model.entries;
acts = model.activities;
hostNames = cellfun(@(x) x.name, hosts, 'UniformOutput', false);
taskNames = cellfun(@(x) x.name, tasks, 'UniformOutput', false);
entryNames = cellfun(@(x) x.name, entries, 'UniformOutput', false);
actNames = cellfun(@(x) x.name, acts, 'UniformOutput', false);

fprintf(fid, '%% LayeredNetwork generated by LQN2MATLAB\n');
fprintf(fid, 'model = LayeredNetwork(%s);\n', q(modelName));
fprintf(fid, 'P = {}; T = {}; E = {}; A = {};\n');

%% processors
fprintf(fid, '\n%%%% Block 1: processors\n');
for p = 1:numel(hosts)
    h = hosts{p};
    hv = sprintf('P{%d}', p);
    ctor = class(h);
    if ~any(strcmp(ctor, {'Processor','Host'}))
        ctor = 'Processor';
    end
    if h.quantum ~= 0.001 || h.speedFactor ~= 1
        fprintf(fid, '%s = %s(model, %s, %s, %s, %s, %s);\n', hv, ctor, q(h.name), ...
            num2code(h.multiplicity), schedCode(h.scheduling), num2code(h.quantum), num2code(h.speedFactor));
    else
        fprintf(fid, '%s = %s(model, %s, %s, %s);\n', hv, ctor, q(h.name), ...
            num2code(h.multiplicity), schedCode(h.scheduling));
    end
    if h.replication ~= 1
        fprintf(fid, '%s.setReplication(%s);\n', hv, num2code(h.replication));
    end
    emitServerExtras(fid, hv, h);
end

%% tasks
fprintf(fid, '\n%%%% Block 2: tasks\n');
for t = 1:numel(tasks)
    tk = tasks{t};
    tv = sprintf('T{%d}', t);
    pidx = find(strcmp(hostNames, tk.parent.name), 1);
    switch class(tk)
        case 'CacheTask'
            fprintf(fid, '%s = CacheTask(model, %s, %s, %s, %s, %s, %s).on(P{%d});\n', tv, q(tk.name), ...
                num2code(tk.items), num2code(tk.itemLevelCap), replCode(tk.replacestrategy), ...
                num2code(tk.multiplicity), schedCode(tk.scheduling), pidx);
            if tk.retrieval
                fprintf(fid, '%s.setRetrieval(true);\n', tv);
            end
        case {'SetupTask','FunctionTask'}
            fprintf(fid, '%s = %s(model, %s, %s, %s).on(P{%d});\n', tv, class(tk), q(tk.name), ...
                num2code(tk.multiplicity), schedCode(tk.scheduling), pidx);
        otherwise
            if ~strcmp(class(tk), 'Task')
                line_warning(mfilename, 'Task %s is a %s, which LQN2MATLAB declares as a plain Task.', tk.name, class(tk));
            end
            fprintf(fid, '%s = Task(model, %s, %s, %s).on(P{%d});\n', tv, q(tk.name), ...
                num2code(tk.multiplicity), schedCode(tk.scheduling), pidx);
    end
    % Task() defaults: think time numeric FineTol (Immediate, mean FineTol), setup/delay-off Immediate() (mean 0)
    if ~isDefaultTime(tk.thinkTime, tk.thinkTimeMean, GlobalConstants.FineTol)
        fprintf(fid, '%s.setThinkTime(%s);\n', tv, timeArg(tk.thinkTime, tk.thinkTimeMean));
    end
    if ~isDefaultTime(tk.setupTime, tk.setupTimeMean, 0)
        fprintf(fid, '%s.setSetupTime(%s);\n', tv, timeArg(tk.setupTime, tk.setupTimeMean));
    end
    if ~isDefaultTime(tk.delayOffTime, tk.delayOffTimeMean, 0)
        fprintf(fid, '%s.setDelayOffTime(%s);\n', tv, timeArg(tk.delayOffTime, tk.delayOffTimeMean));
    end
    if tk.replication ~= 1
        fprintf(fid, '%s.setReplication(%s);\n', tv, num2code(tk.replication));
    end
    if tk.priority ~= 0
        fprintf(fid, '%s.setPriority(%s);\n', tv, num2code(tk.priority));
    end
    if ~isempty(tk.fanInSource)
        fprintf(fid, '%s.setFanIn(%s, %s);\n', tv, q(tk.fanInSource), num2code(tk.fanInValue));
    end
    for fo = 1:numel(tk.fanOutDest)
        fprintf(fid, '%s.setFanOut(%s, %s);\n', tv, q(tk.fanOutDest{fo}), num2code(tk.fanOutValue(fo)));
    end
    emitServerExtras(fid, tv, tk);
end

%% entries
fprintf(fid, '\n%%%% Block 3: entries\n');
for e = 1:numel(entries)
    en = entries{e};
    ev = sprintf('E{%d}', e);
    tidx = find(strcmp(taskNames, en.parent.name), 1);
    if isa(en, 'ItemEntry')
        fprintf(fid, '%s = ItemEntry(model, %s, %s, %s).on(T{%d});\n', ev, q(en.name), ...
            num2code(en.cardinality), dist2code(en.popularity), tidx);
    else
        fprintf(fid, '%s = Entry(model, %s).on(T{%d});\n', ev, q(en.name), tidx);
    end
    if ~strcmp(en.type, 'PH1PH2')
        fprintf(fid, '%s.setType(%s);\n', ev, q(en.type));
    end
    if ~isempty(en.arrival)
        fprintf(fid, '%s.setArrival(%s);\n', ev, dist2code(en.arrival));
    end
end
for e = 1:numel(entries)
    en = entries{e};
    for fw = 1:numel(en.forwardingDests)
        fprintf(fid, 'E{%d}.forward(%s, %s);\n', e, entryRef(en.forwardingDests{fw}, entryNames), ...
            num2code(en.forwardingProbs(fw)));
    end
end

%% activities
fprintf(fid, '\n%%%% Block 4: activities\n');
for a = 1:numel(acts)
    ac = acts{a};
    av = sprintf('A{%d}', a);
    tidx = find(strcmp(taskNames, activityTaskName(ac)), 1);
    bound = '';
    if ~isempty(ac.boundToEntry)
        bound = sprintf('.boundTo(%s)', entryRef(ac.boundToEntry, entryNames));
    end
    fprintf(fid, '%s = Activity(model, %s, %s).on(T{%d})%s;\n', av, q(ac.name), ...
        timeArg(ac.hostDemand, ac.hostDemandMean), tidx, bound);
    if ~strcmp(ac.callOrder, 'STOCHASTIC')
        fprintf(fid, '%s.setCallOrder(%s);\n', av, q(ac.callOrder));
    end
    % Activity() default think time: Immediate.getInstance() with mean FineTol
    if ~isDefaultTime(ac.thinkTime, ac.thinkTimeMean, GlobalConstants.FineTol)
        fprintf(fid, '%s.setThinkTime(%s);\n', av, timeArg(ac.thinkTime, ac.thinkTimeMean));
    end
    if ac.phase ~= 1
        fprintf(fid, '%s.setPhase(%s);\n', av, num2code(ac.phase));
    end
    for s = 1:numel(ac.syncCallDests)
        fprintf(fid, '%s.synchCall(%s, %s);\n', av, entryRef(ac.syncCallDests{s}, entryNames), ...
            num2code(ac.syncCallMeans(s)));
    end
    % the member calls are declared above, so the grouping is recorded without issuing them again
    for g = 1:numel(ac.syncCallGroups)
        grp = ac.syncCallGroups{g};
        fprintf(fid, '%s.recordCallGroup(%s, %s);\n', av, routingCode(grp.strategy), cellstr2code(grp.dests));
    end
    for s = 1:numel(ac.asyncCallDests)
        fprintf(fid, '%s.asynchCall(%s, %s);\n', av, entryRef(ac.asyncCallDests{s}, entryNames), ...
            num2code(ac.asyncCallMeans(s)));
    end
end

%% replies, in each entry's own replyActivity order
fprintf(fid, '\n%%%% Block 5: replies\n');
for e = 1:numel(entries)
    en = entries{e};
    for r = 1:numel(en.replyActivity)
        ractName = en.replyActivity{r};
        k = find(strcmp(actNames, ractName), 1);
        isRef = false;
        if ~isempty(k) && ~isempty(acts{k}.parent) && isa(acts{k}.parent, 'Task')
            isRef = SchedStrategy.fromText(schedText(acts{k}.parent.scheduling)) == SchedStrategy.REF;
        end
        if isempty(k) || isRef
            % repliesTo refuses a reference-task activity, so the reply is recorded directly
            fprintf(fid, 'E{%d}.replyActivity{end+1} = %s;\n', e, q(ractName));
        else
            fprintf(fid, 'A{%d}.repliesTo(E{%d});\n', k, e);
        end
    end
end

%% precedences
fprintf(fid, '\n%%%% Block 6: precedences\n');
for t = 1:numel(tasks)
    tk = tasks{t};
    for ap = 1:numel(tk.precedences)
        fprintf(fid, 'T{%d}.addPrecedence(%s);\n', t, precCode(tk.precedences(ap)));
    end
end
end


function closeIfOwned(fid, ownsFid)
if ownsFid && fid > 2
    fclose(fid);
end
end


function name = activityTaskName(ac)
% NAME = ACTIVITYTASKNAME(AC) the task an activity was declared .on()
if ~isempty(ac.parent) && isa(ac.parent, 'Task')
    name = ac.parent.name;
else
    name = ac.parentName;
end
end


function tf = isDefaultTime(dist, storedMean, defaultMean)
% TF = ISDEFAULTTIME(DIST, STOREDMEAN, DEFAULTMEAN) true for the constructor default
tf = isempty(dist) || (isa(dist, 'Immediate') && storedMean == defaultMean);
end


function s = timeArg(dist, storedMean)
% S = TIMEARG(DIST, STOREDMEAN) argument of a setter that also takes a numeric mean
%
% A numeric argument and a distribution object leave different stored means
% (Immediate: FineTol vs 0; Exp: m vs 1/(1/m)), so the one that reproduces
% STOREDMEAN is chosen.
if isa(dist, 'Immediate')
    if storedMean == 0
        s = 'Immediate()';
    else
        s = '0'; % numeric path: Immediate with mean FineTol
    end
elseif isa(dist, 'Exp') && storedMean ~= dist.getMean() && 1/storedMean == dist.getParam(1).paramValue
    s = num2code(storedMean); % numeric path: Exp(1/m) with mean m
else
    s = dist2code(dist);
end
end


function emitServerExtras(fid, v, el)
% EMITSERVEREXTRAS(FID, V, EL) admission constraints, rate dependence and server pools
if ~isempty(el.linConA)
    fprintf(fid, '%s.setConstraint(%s, %s);\n', v, num2code(el.linConA), num2code(el.linConB));
end
for k = 1:numel(el.linConRows)
    row = el.linConRows{k};
    fprintf(fid, '%s.addConstraint(%s, %s, %s);\n', v, cellstr2code(row.names), num2code(row.coeffs), num2code(row.cap));
end
if ~isempty(el.lldScaling)
    fprintf(fid, '%s.setLoadDependence(%s);\n', v, num2code(el.lldScaling));
end
if ~isempty(el.lcdScaling)
    fprintf(fid, '%s.setClassDependence(%s, %s);\n', v, handle2code(fid, el.lcdScaling, el.name), num2code(el.lcdScalingPeak));
end
if ~isempty(el.ljdScaling)
    fprintf(fid, '%s.setJointDependence(%s, %s);\n', v, handle2code(fid, el.ljdScaling, el.name), num2code(el.ljdScalingPeak));
end
for k = 1:numel(el.serverPools)
    pool = el.serverPools{k};
    fprintf(fid, '%s.addServerType(ServerType(%s, %s, %s, %s));\n', v, q(pool.name), num2code(pool.count), ...
        cellstr2code(pool.compatible), num2code(pool.rate));
end
end


function s = handle2code(fid, f, ownerName)
% S = HANDLE2CODE(FID, F, OWNERNAME) source of a dependence handle, captured numeric values emitted first
s = func2str(f);
if s(1) ~= '@'
    s = ['@', s];
end
info = functions(f);
if isfield(info, 'workspace') && ~isempty(info.workspace)
    ws = info.workspace{1};
    vars = fieldnames(ws);
    for k = 1:numel(vars)
        val = ws.(vars{k});
        if any(strcmp(vars{k}, {'model','P','T','E','A'}))
            line_warning(mfilename, 'The dependence handle of %s captures a variable named %s, which the generated script also uses.', ownerName, vars{k});
        end
        if (isnumeric(val) || islogical(val)) && ndims(val) <= 2 %#ok<ISMAT>
            fprintf(fid, '%s = %s;\n', vars{k}, num2code(val));
        else
            line_warning(mfilename, 'The dependence handle of %s captures %s, a %s that LQN2MATLAB cannot write out.', ownerName, vars{k}, class(val));
        end
    end
end
end


function s = precCode(ap)
% S = PRECCODE(AP) an ActivityPrecedence, by its named factory when one reproduces it exactly
pre = ap.preActs;
post = ap.postActs;
if ap.preType == ActivityPrecedenceType.PRE_SEQ && ap.postType == ActivityPrecedenceType.POST_SEQ && numel(pre) == 1 && numel(post) == 1 ...
        && isempty(ap.preParams) && isempty(ap.postParams)
    s = sprintf('ActivityPrecedence.Serial(%s, %s)', q(pre{1}), q(post{1}));
elseif ap.preType == ActivityPrecedenceType.PRE_AND && ap.postType == ActivityPrecedenceType.POST_SEQ && numel(post) == 1 && isempty(ap.postParams)
    if isempty(ap.preParams)
        s = sprintf('ActivityPrecedence.AndJoin(%s, %s)', cellstr2code(pre), q(post{1}));
    else
        s = sprintf('ActivityPrecedence.AndJoin(%s, %s, %s)', cellstr2code(pre), q(post{1}), num2code(ap.preParams));
    end
elseif ap.preType == ActivityPrecedenceType.PRE_OR && ap.postType == ActivityPrecedenceType.POST_SEQ && numel(post) == 1 ...
        && isempty(ap.preParams) && isempty(ap.postParams)
    s = sprintf('ActivityPrecedence.OrJoin(%s, %s)', cellstr2code(pre), q(post{1}));
elseif ap.preType == ActivityPrecedenceType.PRE_SEQ && ap.postType == ActivityPrecedenceType.POST_AND && numel(pre) == 1 ...
        && isempty(ap.preParams) && isempty(ap.postParams)
    s = sprintf('ActivityPrecedence.AndFork(%s, %s)', q(pre{1}), cellstr2code(post));
elseif ap.preType == ActivityPrecedenceType.PRE_SEQ && ap.postType == ActivityPrecedenceType.POST_OR && numel(pre) == 1 && isempty(ap.preParams)
    s = sprintf('ActivityPrecedence.OrFork(%s, %s, %s)', q(pre{1}), cellstr2code(post), num2code(ap.postParams));
elseif ap.preType == ActivityPrecedenceType.PRE_SEQ && ap.postType == ActivityPrecedenceType.POST_LOOP && numel(pre) == 1 && isempty(ap.preParams)
    % Loop(pre, {body..., end}, counts): the last post activity is the end activity
    s = sprintf('ActivityPrecedence.Loop(%s, %s, %s)', q(pre{1}), cellstr2code(post), num2code(ap.postParams));
elseif ap.preType == ActivityPrecedenceType.PRE_SEQ && ap.postType == ActivityPrecedenceType.POST_CACHE && numel(pre) == 1 ...
        && isempty(ap.preParams) && isempty(ap.postParams)
    s = sprintf('ActivityPrecedence.CacheAccess(%s, %s)', q(pre{1}), cellstr2code(post));
else
    s = sprintf('ActivityPrecedence(%s, %s, %s, %s, %s, %s)', cellstr2code(pre), cellstr2code(post), ...
        precTypeCode(ap.preType), precTypeCode(ap.postType), num2code(ap.preParams), num2code(ap.postParams));
end
end


function s = precTypeCode(type)
% S = PRECTYPECODE(TYPE) ActivityPrecedenceType constant by name
names = {'PRE_SEQ','PRE_AND','PRE_OR','POST_SEQ','POST_AND','POST_OR','POST_LOOP','POST_CACHE'};
for k = 1:numel(names)
    if type == ActivityPrecedenceType.(names{k})
        s = ['ActivityPrecedenceType.', names{k}];
        return
    end
end
s = num2code(type);
end


function s = schedText(sched)
% S = SCHEDTEXT(SCHED) scheduling as text, whether stored as text or as a constant
if isnumeric(sched)
    s = SchedStrategy.toText(sched);
else
    s = char(sched);
end
end


function s = schedCode(sched)
% S = SCHEDCODE(SCHED) SchedStrategy constant that reads back as SCHED
txt = schedText(sched);
id = SchedStrategy.fromText(txt);
s = sprintf('SchedStrategy.fromText(%s)', q(txt));
try
    prop = SchedStrategy.toProperty(txt);
    if SchedStrategy.(prop) == id
        s = ['SchedStrategy.', prop];
    end
catch
    % no constant spells this text, so the fromText form above stands
end
end


function s = replCode(id)
% S = REPLCODE(ID) ReplacementStrategy constant by name
feat = ReplacementStrategy.toFeature(id);
s = strrep(feat, 'ReplacementStrategy_', 'ReplacementStrategy.');
end


function s = routingCode(id)
% S = ROUTINGCODE(ID) RoutingStrategy constant of a call group
if id == RoutingStrategy.RROBIN
    s = 'RoutingStrategy.RROBIN';
elseif id == RoutingStrategy.JSQ
    s = 'RoutingStrategy.JSQ';
else
    line_error(mfilename, sprintf('Call groups carry RROBIN or JSQ; routing strategy %d cannot be written out.', id));
end
end


function s = entryRef(name, entryNames)
% S = ENTRYREF(NAME, ENTRYNAMES) E{k} for a declared entry, else its name
k = find(strcmp(entryNames, name), 1);
if isempty(k)
    s = q(name);
else
    s = sprintf('E{%d}', k);
end
end


function s = dist2code(d)
% S = DIST2CODE(D) constructor call that rebuilds distribution D with the same parameters
if isempty(d)
    s = '[]';
    return
end
par = @(k) d.getParam(k).paramValue;
switch builtin('class', d)
    case 'Immediate'
        s = 'Immediate()';
    case 'Disabled'
        s = 'Disabled()';
    case 'Exp'
        s = sprintf('Exp(%s)', num2code(par(1)));
    case 'Det'
        s = sprintf('Det(%s)', num2code(par(1)));
    case 'Erlang'
        s = sprintf('Erlang(%s, %s)', num2code(par(1)), num2code(par(2)));
    case 'HyperExp'
        p = par(1);
        if isscalar(p)
            s = sprintf('HyperExp(%s, %s, %s)', num2code(p), num2code(par(2)), num2code(par(3)));
        else
            s = sprintf('HyperExp(%s, %s)', num2code(p), num2code(par(2)));
        end
    case {'Gamma','Lognormal','Uniform','Pareto','Normal','Binomial','DiscreteUniform'}
        s = sprintf('%s(%s, %s)', builtin('class', d), num2code(par(1)), num2code(par(2)));
    case 'Weibull'
        % params are (scale alpha, shape r), the constructor takes (shape, scale)
        s = sprintf('Weibull(%s, %s)', num2code(par(2)), num2code(par(1)));
    case {'Geometric','Poisson','Bernoulli'}
        s = sprintf('%s(%s)', builtin('class', d), num2code(par(1)));
    case 'Coxian'
        if numel(d.params) == 3
            s = sprintf('Coxian(%s, %s, %s)', num2code(par(1)), num2code(par(2)), num2code(par(3)));
        else
            s = sprintf('Coxian(%s, %s)', num2code(par(1)), num2code(par(2)));
        end
    case {'PH','APH','MAP','ME','RAP'}
        s = sprintf('%s(%s, %s)', builtin('class', d), num2code(par(1)), num2code(par(2)));
    case 'MMPP2'
        s = sprintf('MMPP2(%s, %s, %s, %s)', num2code(par(1)), num2code(par(2)), num2code(par(3)), num2code(par(4)));
    case 'Zipf'
        s = sprintf('Zipf(%s, %s)', num2code(par(3)), num2code(par(4)));
    case 'DiscreteSampler'
        s = sprintf('DiscreteSampler(%s, %s)', num2code(par(1)), num2code(par(2)));
    case {'Replayer','Trace'}
        s = sprintf('%s(%s)', builtin('class', d), q(par(1)));
    otherwise
        m = d.getMean();
        scv = d.getSCV();
        line_warning(mfilename, 'LQN2MATLAB writes the %s distribution as an APH fitted to its mean and SCV.', builtin('class', d));
        s = sprintf('APH.fitMeanAndSCV(%s, %s)', num2code(m), num2code(scv));
end
end


function s = cellstr2code(c)
% S = CELLSTR2CODE(C) cell array of names
if ischar(c) || isstring(c)
    c = {char(c)};
end
parts = cellfun(@q, c, 'UniformOutput', false);
s = ['{', strjoin(parts, ', '), '}'];
end


function s = num2code(v)
% S = NUM2CODE(V) numeric scalar or matrix at the shortest spelling that reads back as V
if isempty(v)
    s = '[]';
    return
end
if issparse(v)
    v = full(v);
end
if islogical(v) && isscalar(v)
    if v, s = 'true'; else, s = 'false'; end
    return
end
v = double(v);
if isscalar(v)
    s = scalar2code(v);
    return
end
if ndims(v) > 2 %#ok<ISMAT>
    line_error(mfilename, 'LQN2MATLAB cannot write an array of more than two dimensions.');
end
rows = cell(1, size(v,1));
for i = 1:size(v,1)
    rows{i} = strjoin(arrayfun(@scalar2code, v(i,:), 'UniformOutput', false), ', ');
end
s = ['[', strjoin(rows, '; '), ']'];
end


function s = scalar2code(v)
% S = SCALAR2CODE(V) one double, round-trip exact
if isnan(v)
    s = 'NaN';
elseif isinf(v)
    if v > 0, s = 'Inf'; else, s = '-Inf'; end
elseif v == round(v) && abs(v) < 1e15
    s = sprintf('%d', v);
else
    for p = 15:17
        s = sprintf('%.*g', p, v);
        if str2double(s) == v
            return
        end
    end
end
end


function s = q(str)
% S = Q(STR) MATLAB single-quoted literal
s = ['''', strrep(char(str), '''', ''''''), ''''];
end
