"""
Parity tests for the pure Python LSODA port against the C liblsoda reference.

All expected values are generated by compiling and running liblsoda
(sdwfrost/liblsoda) with the same problem parameters and tolerances,
using full-precision (%.15e) output.

Tests cover:
  1. Robertson chemical kinetics (stiff, 3 eqs, classic LSODA benchmark)
  2. Exponential decay (trivial nonstiff, 1 eq, exact solution known)
  3. Linear 2D system (mildly stiff, 2 eqs, exact solution known)
  4. Lotka-Volterra predator-prey (nonstiff oscillator, 2 eqs)
  5. HIRES photochemistry (moderately stiff, 8 eqs)
  6. Van der Pol oscillator (very stiff mu=1000, 2 eqs)
  7. Oregonator (stiff chemical oscillator, 3 eqs)
  8. Conservation law verification (Robertson y1+y2+y3 = 1)
  9. Scalar tolerance interface
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import numpy as np
from line_solver.lib.lsoda import lsoda, lsoda_odeint

# ============================================================================
# Tolerance for parity checks
# ============================================================================
# Python and C may differ slightly due to floating-point evaluation order.
# We use relative tolerance for large values and absolute for small values.
def _check_parity(y_got, y_exp, rtol=1e-4, atol=1e-10):
    """Check if y_got matches y_exp within tolerances.
    Returns (ok, max_rel_err, max_abs_err).
    """
    max_rel = 0.0
    max_abs = 0.0
    ok = True
    for i in range(len(y_exp)):
        ae = abs(y_got[i] - y_exp[i])
        max_abs = max(max_abs, ae)
        if abs(y_exp[i]) > atol:
            re = ae / abs(y_exp[i])
            max_rel = max(max_rel, re)
            if re > rtol:
                ok = False
        else:
            if ae > atol:
                ok = False
    return ok, max_rel, max_abs


def _run_parity_test(name, f, y0, t_span, t_eval, rtol, atol,
                     expected, max_steps=500, check_rtol=1e-4, check_atol=1e-10):
    """Run a parity test against C reference values.
    expected: list of (t, y0, y1, ...) tuples with full-precision C output.
    Returns True if all points match.
    """
    result = lsoda(f, y0, t_span, t_eval=t_eval, rtol=rtol, atol=atol,
                   max_steps=max_steps)
    if not result.success:
        print(f"  FAIL: solver failed - {result.message}")
        return False

    neq = len(y0)
    all_pass = True
    max_rel_total = 0.0
    max_abs_total = 0.0

    for idx, exp_row in enumerate(expected):
        t_exp = exp_row[0]
        y_exp = list(exp_row[1:])
        y_got = result.y[idx + 1]  # +1 because y[0] is initial state

        ok, max_rel, max_abs = _check_parity(y_got, y_exp, check_rtol, check_atol)
        max_rel_total = max(max_rel_total, max_rel)
        max_abs_total = max(max_abs_total, max_abs)

        if not ok:
            all_pass = False
            print(f"  FAIL at t={t_exp:.4e}: max_rel={max_rel:.2e}")
            for j in range(neq):
                if abs(y_exp[j]) > check_atol:
                    re = abs(y_got[j] - y_exp[j]) / abs(y_exp[j])
                else:
                    re = abs(y_got[j] - y_exp[j])
                flag = " <--" if re > check_rtol else ""
                print(f"    y[{j}]: got={y_got[j]:.15e} exp={y_exp[j]:.15e} err={re:.2e}{flag}")

    status = "PASS" if all_pass else "FAIL"
    print(f"  {status}: max_rel_err={max_rel_total:.2e}, nst={result.nst}, nfe={result.nfe}, nje={result.nje}")
    return all_pass


# ============================================================================
# Test 1: Robertson chemical kinetics (stiff)
# ============================================================================
def test_robertson():
    """Robertson problem: classic stiff ODE benchmark (3 eqs).
    dy1/dt = -0.04*y1 + 1e4*y2*y3
    dy2/dt = 0.04*y1 - 1e4*y2*y3 - 3e7*y2^2
    dy3/dt = 3e7*y2^2
    """
    def f(t, y, ydot, data):
        ydot[0] = 1.0e4 * y[1] * y[2] - 0.04 * y[0]
        ydot[2] = 3.0e7 * y[1] * y[1]
        ydot[1] = -(ydot[0] + ydot[2])

    y0 = [1.0, 0.0, 0.0]
    t_eval = [0.4 * 10.0 ** i for i in range(12)]

    # C reference output (%.15e precision)
    expected = [
        (4e-01, 9.851712049052344e-01, 3.386380058450371e-05, 1.479493129418126e-02),
        (4e+00, 9.055332934421416e-01, 2.240655242773938e-05, 9.444430000543071e-02),
        (4e+01, 7.158403474138746e-01, 9.186333848221152e-06, 2.841504662522774e-01),
        (4e+02, 4.505250299518244e-01, 3.222963773719375e-06, 5.494717470844018e-01),
        (4e+03, 1.831975696546021e-01, 8.941773261377527e-07, 8.168015361680721e-01),
        (4e+04, 3.898729244522436e-02, 1.621939581471608e-07, 9.610125453607797e-01),
        (4e+05, 4.936362159709025e-03, 1.984220853834811e-08, 9.950636179980765e-01),
        (4e+06, 5.161832921225141e-04, 2.065786542448266e-09, 9.994838146420849e-01),
        (4e+07, 5.179803644367760e-05, 2.072026913293681e-10, 9.999482017563474e-01),
        (4e+08, 5.283686292063946e-06, 2.113485306887202e-11, 9.999947162925692e-01),
        (4e+09, 4.658646268319763e-07, 1.863459326277758e-12, 9.999995341335010e-01),
        (4e+10, 1.431681921554496e-08, 5.726732909838437e-14, 9.999999856831133e-01),
    ]

    # Robertson uses rtol=1e-4 for integration. The C and Python FP
    # evaluation paths diverge at extreme time scales (t=4e10) for
    # near-zero values (~1e-8), so we allow 0.5% relative tolerance
    # which is well within the integration accuracy.
    return _run_parity_test("Robertson", f, y0, (0.0, t_eval[-1]), t_eval,
                            rtol=[1e-4]*3, atol=[1e-6, 1e-10, 1e-6],
                            expected=expected, check_rtol=5e-3, check_atol=1e-8)


# ============================================================================
# Test 2: Exponential decay (nonstiff, exact solution)
# ============================================================================
def test_exponential_decay():
    """dy/dt = -y, y(0)=1. Exact: y(t) = exp(-t)."""
    def f(t, y, ydot, data):
        ydot[0] = -y[0]

    y0 = [1.0]
    t_eval = [0.5, 1.0, 2.0, 5.0, 10.0]

    # C reference output
    expected = [
        (5e-01, 6.065306706955518e-01),
        (1e+00, 3.678794480345809e-01),
        (2e+00, 1.353352828204701e-01),
        (5e+00, 6.737947209171920e-03),
        (1e+01, 4.539994917152099e-05),
    ]

    ok = _run_parity_test("ExponentialDecay", f, y0, (0.0, 10.0), t_eval,
                          rtol=[1e-8], atol=[1e-10],
                          expected=expected, check_rtol=1e-6)

    # Also verify against exact solution
    if ok:
        result = lsoda(f, y0, (0.0, 10.0), t_eval=t_eval, rtol=[1e-8], atol=[1e-10])
        for idx, t in enumerate(t_eval):
            exact = np.exp(-t)
            err = abs(result.y[idx + 1][0] - exact) / exact
            if err > 1e-6:
                print(f"  FAIL vs exact at t={t}: err={err:.2e}")
                ok = False
        if ok:
            print("  Exact solution check: PASS")
    return ok


# ============================================================================
# Test 3: Linear 2D system (exact solution available)
# ============================================================================
def test_linear_2d():
    """dy1/dt = -0.04*y1, dy2/dt = 0.04*y1 - 0.0004*y2.
    y1(0)=100, y2(0)=0.
    Exact: y1(t) = 100*exp(-0.04*t)
           y2(t) = 100*(0.04/(0.04-0.0004))*(exp(-0.0004*t) - exp(-0.04*t))
    """
    def f(t, y, ydot, data):
        ydot[0] = -0.04 * y[0]
        ydot[1] = 0.04 * y[0] - 0.0004 * y[1]

    y0 = [100.0, 0.0]
    t_eval = [10.0, 25.0, 50.0, 100.0, 200.0]

    # C reference output
    expected = [
        (1e+01, 6.703200486744036e+01, 3.289777178480690e+01),
        (2.5e+01, 3.678794391922581e+01, 6.284549439968792e+01),
        (5e+01, 1.353352809382181e+01, 8.533973660288261e+01),
        (1e+02, 1.831563895789600e+00, 9.519937375701294e+01),
        (2e+02, 3.354626444786475e-02, 9.321019027698564e+01),
    ]

    ok = _run_parity_test("Linear2D", f, y0, (0.0, 200.0), t_eval,
                          rtol=[1e-8]*2, atol=[1e-10]*2,
                          expected=expected, check_rtol=1e-6)

    # Verify against exact solution
    if ok:
        result = lsoda(f, y0, (0.0, 200.0), t_eval=t_eval, rtol=[1e-8]*2, atol=[1e-10]*2)
        max_err = 0.0
        for idx, t in enumerate(t_eval):
            y1_exact = 100.0 * np.exp(-0.04 * t)
            k1, k2 = 0.04, 0.0004
            y2_exact = 100.0 * (k1 / (k1 - k2)) * (np.exp(-k2 * t) - np.exp(-k1 * t))
            for j, ye in enumerate([y1_exact, y2_exact]):
                if abs(ye) > 1e-10:
                    err = abs(result.y[idx + 1][j] - ye) / abs(ye)
                    max_err = max(max_err, err)
        if max_err < 1e-6:
            print(f"  Exact solution check: PASS (max_rel_err={max_err:.2e})")
        else:
            print(f"  Exact solution check: FAIL (max_rel_err={max_err:.2e})")
            ok = False
    return ok


# ============================================================================
# Test 4: Lotka-Volterra predator-prey (nonstiff)
# ============================================================================
def test_lotka_volterra():
    """Lotka-Volterra: dx/dt = a*x - b*x*y, dy/dt = -c*y + d*x*y.
    a=1.5, b=1, c=3, d=1. Nonstiff oscillator.
    """
    def f(t, y, ydot, data):
        a, b, c, d = 1.5, 1.0, 3.0, 1.0
        ydot[0] = a * y[0] - b * y[0] * y[1]
        ydot[1] = -c * y[1] + d * y[0] * y[1]

    y0 = [1.0, 0.5]
    t_eval = [1.0, 2.0, 5.0, 10.0, 20.0]

    # C reference output
    expected = [
        (1e+00, 3.470510611484247e+00, 1.733367600347866e-01),
        (2e+00, 6.248112872035267e+00, 3.785024743989394e+00),
        (5e+00, 6.757429433824432e+00, 5.130001976558919e-01),
        (1e+01, 7.584538961510633e-01, 1.114628189914375e+00),
        (2e+01, 8.324599499638285e-01, 2.577212173483628e+00),
    ]

    return _run_parity_test("LotkaVolterra", f, y0, (0.0, 20.0), t_eval,
                            rtol=[1e-8]*2, atol=[1e-10]*2,
                            expected=expected, check_rtol=1e-6)


# ============================================================================
# Test 5: HIRES photochemistry (moderately stiff, 8 eqs)
# ============================================================================
def test_hires():
    """HIRES (High Irradiance RESponses of photomorphogenesis).
    8-equation moderately stiff chemical kinetics system.
    Standard test problem from Hairer & Wanner.
    """
    def f(t, y, ydot, data):
        ydot[0] = -1.71*y[0] + 0.43*y[1] + 8.32*y[2] + 0.0007
        ydot[1] = 1.71*y[0] - 8.75*y[1]
        ydot[2] = -10.03*y[2] + 0.43*y[3] + 0.035*y[4]
        ydot[3] = 8.32*y[1] + 1.71*y[2] - 1.12*y[3]
        ydot[4] = -1.745*y[4] + 0.43*y[5] + 0.43*y[6]
        ydot[5] = -280.0*y[5]*y[7] + 0.69*y[3] + 1.71*y[4] - 0.43*y[5] + 0.69*y[6]
        ydot[6] = 280.0*y[5]*y[7] - 1.81*y[6]
        ydot[7] = -280.0*y[5]*y[7] + 1.81*y[6]

    y0 = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0057]
    t_eval = [100.0, 200.0, 321.8122]

    # C reference output
    expected = [
        (1e+02,
         4.520862869231245e-03, 8.839063180882597e-04, 7.971949677087163e-04,
         7.811332285106224e-03, 1.323853727051267e-01, 5.301681739823277e-01,
         5.631339591581244e-03, 6.866040841874939e-05),
        (2e+02,
         2.736525896095168e-03, 5.351908569598239e-04, 4.485119404720507e-04,
         4.688161408919465e-03, 7.083443534644768e-02, 2.804641383048971e-01,
         5.571599220744725e-03, 1.284007792552683e-04),
        (3.218122e+02,
         7.371423243758239e-04, 1.442507544489246e-04, 5.888935680491721e-05,
         1.175672019019430e-03, 2.386687478330434e-03, 6.239970967822740e-03,
         2.850266805796065e-03, 2.849733194203930e-03),
    ]

    return _run_parity_test("HIRES", f, y0, (0.0, 321.8122), t_eval,
                            rtol=[1e-6]*8, atol=[1e-8]*8,
                            expected=expected, check_rtol=1e-4)


# ============================================================================
# Test 6: Van der Pol oscillator (very stiff, mu=1000)
# ============================================================================
def test_vanderpol():
    """Van der Pol oscillator with mu=1000 (very stiff).
    dy1/dt = y2, dy2/dt = mu*(1-y1^2)*y2 - y1.
    No C reference (too large), but verify solver completes successfully
    and solution stays bounded.
    """
    mu = 1000.0

    def f(t, y, ydot, data):
        ydot[0] = y[1]
        ydot[1] = mu * (1.0 - y[0] * y[0]) * y[1] - y[0]

    y0 = [2.0, 0.0]
    t_end = 3000.0
    t_eval = np.linspace(0, t_end, 100)[1:]

    result = lsoda(f, y0, (0.0, t_end), t_eval=t_eval,
                   rtol=1e-6, atol=1e-8, max_steps=100000)

    ok = result.success
    if not ok:
        print(f"  FAIL: solver failed - {result.message}")
        return False

    # Check solution stays bounded (Van der Pol has limit cycle with |y1| <= ~2.1)
    y_max = np.max(np.abs(result.y[:, 0]))
    if y_max > 2.5:
        print(f"  FAIL: y1 exceeded expected bound: max|y1|={y_max:.4f}")
        ok = False

    print(f"  PASS: nst={result.nst}, nfe={result.nfe}, nje={result.nje}, max|y1|={y_max:.4f}")
    return ok


# ============================================================================
# Test 7: Oregonator (stiff chemical oscillator)
# ============================================================================
def test_oregonator():
    """Oregonator model for Belousov-Zhabotinsky reaction.
    3 equations, stiff. Requires many steps.
    Verify solver can handle it (with increased max_steps).
    """
    def f(t, y, ydot, data):
        s = 77.27
        w = 0.161
        q = 8.375e-6
        ydot[0] = s * (y[1] - y[0]*y[1] + y[0] - q*y[0]*y[0])
        ydot[1] = (-y[1] - y[0]*y[1] + y[2]) / s
        ydot[2] = w * (y[0] - y[2])

    y0 = [1.0, 2.0, 3.0]
    t_eval = [50.0, 100.0, 200.0, 300.0, 360.0]

    result = lsoda(f, y0, (0.0, 360.0), t_eval=t_eval,
                   rtol=[1e-6]*3, atol=[1e-8]*3, max_steps=5000)

    ok = result.success
    if not ok:
        print(f"  FAIL: solver failed - {result.message}")
        return False

    # Verify solution is positive and bounded
    for idx, t in enumerate(t_eval):
        yv = result.y[idx + 1]
        if any(yv < -1e-8):
            print(f"  FAIL: negative values at t={t}: {yv}")
            ok = False

    print(f"  PASS: nst={result.nst}, nfe={result.nfe}, nje={result.nje}")
    return ok


# ============================================================================
# Test 8: Conservation law (Robertson y1+y2+y3 = 1)
# ============================================================================
def test_conservation_law():
    """Verify Robertson problem conserves mass: y1+y2+y3 = 1 at all times."""
    def f(t, y, ydot, data):
        ydot[0] = 1.0e4 * y[1] * y[2] - 0.04 * y[0]
        ydot[2] = 3.0e7 * y[1] * y[1]
        ydot[1] = -(ydot[0] + ydot[2])

    y0 = [1.0, 0.0, 0.0]
    t_eval = [0.4 * 10.0 ** i for i in range(12)]

    result = lsoda(f, y0, (0.0, t_eval[-1]), t_eval=t_eval,
                   rtol=[1e-4]*3, atol=[1e-6, 1e-10, 1e-6])

    if not result.success:
        print(f"  FAIL: solver failed - {result.message}")
        return False

    max_drift = 0.0
    for idx in range(len(result.t)):
        total = sum(result.y[idx])
        drift = abs(total - 1.0)
        max_drift = max(max_drift, drift)

    ok = max_drift < 1e-8
    status = "PASS" if ok else "FAIL"
    print(f"  {status}: max conservation drift = {max_drift:.2e}")
    return ok


# ============================================================================
# Test 9: Scalar tolerance interface
# ============================================================================
def test_scalar_tolerances():
    """Verify that scalar rtol/atol work the same as per-component arrays."""
    def f(t, y, ydot, data):
        ydot[0] = -0.04 * y[0]
        ydot[1] = 0.04 * y[0] - 0.0004 * y[1]

    y0 = [100.0, 0.0]
    t_eval = [10.0, 50.0, 100.0]

    # Run with scalar tolerances
    r1 = lsoda(f, y0, (0.0, 100.0), t_eval=t_eval, rtol=1e-8, atol=1e-10)
    # Run with array tolerances (same values)
    r2 = lsoda(f, y0, (0.0, 100.0), t_eval=t_eval, rtol=[1e-8]*2, atol=[1e-10]*2)

    if not r1.success or not r2.success:
        print(f"  FAIL: solver failed")
        return False

    max_diff = 0.0
    for idx in range(len(r1.t)):
        diff = np.max(np.abs(r1.y[idx] - r2.y[idx]))
        max_diff = max(max_diff, diff)

    ok = max_diff < 1e-14
    status = "PASS" if ok else "FAIL"
    print(f"  {status}: max diff between scalar/array tolerances = {max_diff:.2e}")
    return ok


# ============================================================================
# Test 10: odeint convenience interface vs lsoda()
# ============================================================================
def test_odeint_parity():
    """Verify lsoda_odeint gives same results as lsoda for decay problem."""
    def f_lsoda(t, y, ydot, data):
        ydot[0] = -y[0]
        ydot[1] = -2.0 * y[1]

    def f_odeint(t, y):
        return [-y[0], -2.0 * y[1]]

    y0 = [1.0, 1.0]
    t_eval = np.array([0.0, 0.5, 1.0, 2.0, 5.0])

    r1 = lsoda(f_lsoda, y0, (0.0, 5.0), t_eval=t_eval[1:], rtol=1e-8, atol=1e-10)
    r2 = lsoda_odeint(f_odeint, y0, t_eval, rtol=1e-8, atol=1e-10)

    if not r1.success or not r2.success:
        print(f"  FAIL: solver failed")
        return False

    # Both should have same number of output points
    max_diff = 0.0
    for idx in range(min(len(r1.y), len(r2.y))):
        diff = np.max(np.abs(r1.y[idx] - r2.y[idx]))
        max_diff = max(max_diff, diff)

    # Also check against exact solution
    max_exact_err = 0.0
    for idx, t in enumerate(t_eval):
        y_exact = np.array([np.exp(-t), np.exp(-2.0 * t)])
        err = np.max(np.abs(r2.y[idx] - y_exact))
        max_exact_err = max(max_exact_err, err)

    ok = max_diff < 1e-12 and max_exact_err < 1e-6
    status = "PASS" if ok else "FAIL"
    print(f"  {status}: lsoda/odeint diff={max_diff:.2e}, exact err={max_exact_err:.2e}")
    return ok


# ============================================================================
# Test 11: Backward integration (negative time direction)
# ============================================================================
def test_backward_integration():
    """dy/dt = -y integrated backward: from t=5 to t=0.
    y(5) = exp(-5), should recover y(0) = 1.
    """
    def f(t, y, ydot, data):
        ydot[0] = -y[0]

    y0 = [np.exp(-5.0)]
    t_eval = [4.0, 2.0, 0.0]

    result = lsoda(f, y0, (5.0, 0.0), t_eval=t_eval, rtol=1e-8, atol=1e-10)

    if not result.success:
        print(f"  FAIL: solver failed - {result.message}")
        return False

    # At t=0, should get y=1
    y_final = result.y[-1][0]
    err = abs(y_final - 1.0)

    ok = err < 1e-6
    status = "PASS" if ok else "FAIL"
    print(f"  {status}: y(0)={y_final:.15e}, err={err:.2e}")
    return ok


# ============================================================================
# Test 12: Large system (50 coupled equations)
# ============================================================================
def test_large_system():
    """50-equation coupled decay chain: dy_i/dt = -alpha_i * y_i + alpha_{i-1} * y_{i-1}.
    Tests that dgefa/dgesl work correctly for larger matrices.
    """
    N = 50
    alphas = np.linspace(0.01, 1.0, N)

    def f(t, y, ydot, data):
        ydot[0] = -alphas[0] * y[0]
        for i in range(1, N):
            ydot[i] = alphas[i - 1] * y[i - 1] - alphas[i] * y[i]

    y0 = np.zeros(N)
    y0[0] = 1.0
    t_eval = [1.0, 10.0, 100.0]

    result = lsoda(f, y0, (0.0, 100.0), t_eval=t_eval,
                   rtol=1e-6, atol=1e-8, max_steps=5000)

    if not result.success:
        print(f"  FAIL: solver failed - {result.message}")
        return False

    # Conservation: sum of all y_i should be 1 (closed chain) or decreasing
    # Actually this is an open chain (last element decays), so sum < 1
    # Just check positivity and boundedness
    ok = True
    for idx in range(len(result.t)):
        yv = result.y[idx]
        if np.any(yv < -1e-8):
            print(f"  FAIL: negative values at t={result.t[idx]}")
            ok = False
        if np.any(yv > 1.1):
            print(f"  FAIL: values exceeded initial at t={result.t[idx]}")
            ok = False

    status = "PASS" if ok else "FAIL"
    print(f"  {status}: nst={result.nst}, nfe={result.nfe}, nje={result.nje}")
    return ok


# ============================================================================
# Main
# ============================================================================
TESTS = [
    ("Robertson chemical kinetics (stiff, 3 eqs)", test_robertson),
    ("Exponential decay (nonstiff, exact solution)", test_exponential_decay),
    ("Linear 2D system (exact solution)", test_linear_2d),
    ("Lotka-Volterra (nonstiff oscillator)", test_lotka_volterra),
    ("HIRES photochemistry (stiff, 8 eqs)", test_hires),
    ("Van der Pol (very stiff, mu=1000)", test_vanderpol),
    ("Oregonator (stiff oscillator)", test_oregonator),
    ("Conservation law (Robertson)", test_conservation_law),
    ("Scalar tolerance interface", test_scalar_tolerances),
    ("odeint interface parity", test_odeint_parity),
    ("Backward integration", test_backward_integration),
    ("Large system (50 eqs)", test_large_system),
]


if __name__ == "__main__":
    n_pass = 0
    n_fail = 0
    results = []

    for i, (name, test_fn) in enumerate(TESTS):
        print(f"[{i+1}/{len(TESTS)}] {name}")
        try:
            ok = test_fn()
        except Exception as e:
            print(f"  FAIL: exception - {e}")
            ok = False
        results.append((name, ok))
        if ok:
            n_pass += 1
        else:
            n_fail += 1
        print()

    print("=" * 72)
    print(f"RESULTS: {n_pass} PASS, {n_fail} FAIL out of {len(TESTS)} tests")
    print("=" * 72)
    if n_fail > 0:
        print("FAILED tests:")
        for name, ok in results:
            if not ok:
                print(f"  - {name}")
        sys.exit(1)
    else:
        print("ALL TESTS PASSED")
