/*
 * Copyright (c) 2012-2026, QORE Lab, Imperial College London
 * All rights reserved.
 */

package jline;

/**
 * Enumeration for specifying solver verbosity levels.
 * 
 * <p>Controls the amount of output generated by solvers during execution:
 * <ul>
 *   <li>{@code SILENT} - No output, completely quiet operation</li>
 *   <li>{@code STD} - Standard output, normal operation messages</li>
 *   <li>{@code DEBUG} - Verbose output, detailed debugging information</li>
 * </ul>
 * </p>
 * 
 * @see GlobalConstants#setVerbose(VerboseLevel)
 * @see GlobalConstants#getVerbose()
 */
public enum VerboseLevel {
    /** No output during solver execution */
    SILENT,
    /** Standard output level with essential messages */
    STD,
    /** Verbose debugging output with detailed trace information */
    DEBUG
}