/*
 * Copyright (c) 2012-2026, QORE Lab, Imperial College London
 * All rights reserved.
 */

package jline.io.tikz;

/**
 * Configuration options for TikZ network visualization.
 */
public class TikZOptions {

    /** Vertical spacing between nodes within the same layer (in cm) */
    private double nodeSpacing = 3.0;

    /** Horizontal spacing between layers (in cm) */
    private double layerSpacing = 4.0;

    /** Whether to show routing probabilities on edges */
    private boolean showRoutingProb = true;

    /** Whether to show server count for queues */
    private boolean showServerCount = true;

    /** Whether to show node names as labels */
    private boolean showNodeNames = true;

    /** Whether to show scheduling strategy for queues */
    private boolean showScheduling = true;

    /** Border padding around the diagram (in pt) */
    private int borderPadding = 10;

    /** Minimum probability to display (smaller values are hidden) */
    private double minProbToShow = 0.001;

    /** Whether to hide auto-generated nodes like ClassSwitch for class-switching routing */
    private boolean hideAutoGeneratedNodes = false;

    public TikZOptions() {
    }

    // Getters and setters

    public double getNodeSpacing() {
        return nodeSpacing;
    }

    public TikZOptions setNodeSpacing(double nodeSpacing) {
        this.nodeSpacing = nodeSpacing;
        return this;
    }

    public double getLayerSpacing() {
        return layerSpacing;
    }

    public TikZOptions setLayerSpacing(double layerSpacing) {
        this.layerSpacing = layerSpacing;
        return this;
    }

    public boolean isShowRoutingProb() {
        return showRoutingProb;
    }

    public TikZOptions setShowRoutingProb(boolean showRoutingProb) {
        this.showRoutingProb = showRoutingProb;
        return this;
    }

    public boolean isShowServerCount() {
        return showServerCount;
    }

    public TikZOptions setShowServerCount(boolean showServerCount) {
        this.showServerCount = showServerCount;
        return this;
    }

    public boolean isShowNodeNames() {
        return showNodeNames;
    }

    public TikZOptions setShowNodeNames(boolean showNodeNames) {
        this.showNodeNames = showNodeNames;
        return this;
    }

    public boolean isShowScheduling() {
        return showScheduling;
    }

    public TikZOptions setShowScheduling(boolean showScheduling) {
        this.showScheduling = showScheduling;
        return this;
    }

    public int getBorderPadding() {
        return borderPadding;
    }

    public TikZOptions setBorderPadding(int borderPadding) {
        this.borderPadding = borderPadding;
        return this;
    }

    public double getMinProbToShow() {
        return minProbToShow;
    }

    public TikZOptions setMinProbToShow(double minProbToShow) {
        this.minProbToShow = minProbToShow;
        return this;
    }

    public boolean isHideAutoGeneratedNodes() {
        return hideAutoGeneratedNodes;
    }

    public TikZOptions setHideAutoGeneratedNodes(boolean hideAutoGeneratedNodes) {
        this.hideAutoGeneratedNodes = hideAutoGeneratedNodes;
        return this;
    }
}
